### ISSUE TITLE
deploy_and_upgrade_test.go needs cases that initialize the cluster with 2.0 / 2.19 / 3.0

### ISSUE THREAD

**Issue by jimdickinson** [opensearch-project/opensearch-k8s-operator#1016]
I'm working on some operator changes we need, and the functional test always fails since I changed it to initialize a 2.18 cluster and upgrade to 2.19. Going through the yaml I realize the input is legal for 1.x, but not really legal for 2.x because an admin password is required now.

Adding
```
  security:
    config:
    tls:
       http:
         generate: true
       transport:
         generate: true
         perNode: true
```

and

```
    setVMMaxMapCount: true
```

to opensearch-operator/functionaltests/operatortests/deploy-and-upgrade.yaml allows the test to pass.
