### ISSUE TITLE
[BUG] coordinator role not deploying

### ISSUE THREAD

**Issue by bjolo** [opensearch-project/opensearch-k8s-operator#1023]
### What is the bug?
we want to setup dedicated coordinator nodes in the cluster. according to docs, that should be done by setting the node.roles: [], but that does not seem to work properly. Our coordinator nodes gets node.role dimr

### How can one reproduce the bug?
values.yaml 
    - component: coordinators
      roles: []
      replicas: 2    
      diskSize: "10Gi"    
      persistence: 
        pvc:
          storageClass: "mayastor-nvme-rep3"
          accessModes:
            - ReadWriteOnce
      jvm: -Xmx4G -Xms4G    
      resources:    
         requests:    
            memory: "4Gi"    
            cpu: "2"    
         limits:    
            memory: "8Gi"    
            cpu: "8"    

GET _cat/nodes?v | grep coordinators
ip             heap.percent ram.percent cpu load_1m load_5m load_15m node.role node.roles                                        cluster_manager name
10.233.70.250            11          57   1    4.31    3.89     3.54 dimr      cluster_manager,data,ingest,remote_cluster_client -               opensearch-prod-coordinators-0
10.233.116.208           35          59   1    2.70    3.15     3.40 dimr      cluster_manager,data,ingest,remote_cluster_client *               opensearch-prod-coordinators-1

### What is the expected behavior?
the expected behavior is that they should only have the role "-"

### What is your host/environment?
rocky linux 9
k8s 1.30.10
helm search repo opensearch-operator
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION                                      
opensearch-operator/opensearch-operator 2.7.0           2.7.0           The OpenSearch Operator Helm chart for Kubernetes
opensearch-operator/opensearch-cluster  3.0.0           2.7.0           A Helm chart for OpenSearch Cluster      

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by vinylen** [comment]
We ran into this as well, setting roles to ingest for now as i saw it being suggested somewhere.
```
    roles:
      - ingest
```

Edit: Relevant https://github.com/opensearch-project/opensearch-k8s-operator/discussions/1015#discussion-8355612

**Comment by bjolo** [comment]
hi vinylen,

thanks for tip, but we also have dedicated ingest nodes so that kinda does not work for us. i saw someone else that used the role remote_cluster_client, perhaps that could do as a workaround for us

**Comment by rishabh6788** [comment]
Tagging @prudhvigodithi for traction

**Comment by YeonghyeonKO** [comment]
@bjolo @vinylen ,
I tested to create coordinating-only nodes with the below manifest, and it worked.
Please append 4 pairs of `{key}:false` for `node.data`, `node.ingest`, `node.master`, `node.remote_cluster_client` respectively to `additionalConfig`. Don't forget to make specify `nodePools[].roles` empty.
```yaml
  - additionalConfig:
      node.data: "false"
      node.ingest: "false"
      node.master: "false"
      node.remote_cluster_client: "false"
    component: coordinating
    ...
    roles:
    - ""
```

**Comment by fpc7063** [comment]
Confirmed node.roles has no value:
```yaml
    - name: OPENSEARCH_JAVA_OPTS
      value: -Xmx1024M -Xms1024M -Dopensearch.transport.cname_in_publish_address=true
    - name: node.roles
    - name: http.port
      value: "9200"
```

Just checked, node.roles is empty on the pod config when using:
```yaml
roles: []
```
```yaml
roles:
  - "[]"
```
\
\
For example, editing the generated statefulset:
```yaml
- name: node.roles
  value: '[]'
```
Results in:
```
10.244.2.92           14          68  12    1.75    1.86     1.76 -         []                   -               teste-coordinations-0
```
\
For example, also editing the generated statefulset:
```yaml
- name: node.roles
  value: ''
```
Results in:
```
10.244.2.93           16          68  72    1.79    1.87     1.79 dimr      cluster_manager,data,ingest,remote_cluster_client -               teste-coordinations-0
```

**Comment by fpc7063** [comment]
Docs say explicitly:  `node.roles: []`
https://docs.opensearch.org/docs/latest/tuning-your-cluster/#step-2-set-node-attributes-for-each-node-in-a-cluster

**Comment by YeonghyeonKO** [comment]
Hi @fpc7063 ! Did you host the OpenSearch cluster using `opensearchclusters.opensearch.opster.io` CRD?

**Comment by fpc7063** [comment]
Yeah, helm chart. I manually patched the Statefulset for testing. I know this because i have "from scratch" clusters

**Comment by fpc7063** [comment]
Sadly the operator tests marks [coodination nodes with ingest roles](https://github.com/opensearch-project/opensearch-k8s-operator/blob/61fae951a751fa5507a8a8854ca10547ff7c5398/opensearch-operator/examples/2.x/opensearch-cluster-pdb.yaml#L58)

**Comment by fpc7063** [comment]
> [@bjolo](https://github.com/bjolo) [@vinylen](https://github.com/vinylen) , I tested to create coordinating-only nodes with the below manifest, and it worked. Please append 4 pairs of `{key}:false` for `node.data`, `node.ingest`, `node.master`, `node.remote_cluster_client` respectively to `additionalConfig`. Don't forget to make specify `nodePools[].roles` empty.
> 
>   - additionalConfig:
>       node.data: "false"
>       node.ingest: "false"
>       node.master: "false"
>       node.remote_cluster_client: "false"
>     component: coordinating
>     ...
>     roles:
>     - ""

Your suggestion throws a lot of deprecation warnings about these options, not sure if they are still valid in 3.0.0

**Comment by YeonghyeonKO** [comment]
When drilling down into the manifest of Pod-level (from the CRD I've created), it's same with your reply.
> Confirmed node.roles has no value:
> 
>     - name: OPENSEARCH_JAVA_OPTS
>       value: -Xmx1024M -Xms1024M -Dopensearch.transport.cname_in_publish_address=true
>     - name: node.roles
>     - name: http.port
>       value: "9200"


- Pod spec
```
spec:
  containers:
  - command:
    - /bin/bash
    - -c
    - ./opensearch-docker-entrypoint.sh
    env:
    - name: cluster.initial_master_nodes
      value: test-opensearch-cluster-v2-17-1-bootstrap-0
    - name: discovery.seed_hosts
      value: test-opensearch-cluster-v2-17-1-discovery
    - name: cluster.name
      value: test-opensearch-cluster-v2-17-1
    - name: network.bind_host
      value: 0.0.0.0
    - name: network.publish_host
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: OPENSEARCH_JAVA_OPTS
      value: -Xmx8192M -Xms8192M -Dopensearch.transport.cname_in_publish_address=true
    - name: node.roles
    - name: http.port
      value: "9200"
    - name: node.data
      value: "false"
    - name: node.ingest
      value: "false"
    - name: node.master
      value: "false"
    - name: node.remote_cluster_client
      value: "false"
```

**Comment by YeonghyeonKO** [comment]
> Your suggestion throws a lot of deprecation warnings about these options, not sure if they are still valid in 3.0.0

Can you show me warning logs here? I will test if coordinating-only nodes would be created in 3.0.0

**Comment by YeonghyeonKO** [comment]
> Sadly the operator tests marks [coodination nodes with ingest roles](https://github.com/opensearch-project/opensearch-k8s-operator/blob/61fae951a751fa5507a8a8854ca10547ff7c5398/opensearch-operator/examples/2.x/opensearch-cluster-pdb.yaml#L58)

I think this example may be confusing to beginners who aren't familiar with the difference between Ingest and Coordinating roles.

**Comment by fpc7063** [comment]
Logs when setting roles through `additionalConfig` as you suggested, Tested versions: "2.3.0" and "2.19.2"
```
teste-coordinations-0 opensearch [2025-06-22T21:37:43,435][DEPRECATION][o.o.d.c.s.Settings       ] [teste-coordinations-0] [node.master] setting was deprecated in OpenSearch and will be removed in a future release! See the breaking changes documentation for the next major version.
teste-coordinations-0 opensearch [2025-06-22T21:37:43,436][DEPRECATION][o.o.d.c.s.Settings       ] [teste-coordinations-0] [node.data] setting was deprecated in OpenSearch and will be removed in a future release! See the breaking changes documentation for the next major version.
teste-coordinations-0 opensearch [2025-06-22T21:37:43,436][DEPRECATION][o.o.d.c.s.Settings       ] [teste-coordinations-0] [node.remote_cluster_client] setting was deprecated in OpenSearch and will be removed in a future release! See the breaking changes documentation for the next major version.
teste-coordinations-0 opensearch [2025-06-22T21:37:43,436][DEPRECATION][o.o.d.c.s.Settings       ] [teste-coordinations-0] [node.ingest] setting was deprecated in OpenSearch and will be removed in a future release! See the breaking changes documentation for the next major version.
```

**Comment by fpc7063** [comment]
3.0.0 works fine as well, same deprecation warning. I don't think it requires
```yaml
roles:
- []
```
This does the job aswell: `roles: []`

Inflated CRD
```yaml
[...]
- additionalConfig:
        node.data: "false"
        node.ingest: "false"
        node.master: "false"
        node.remote_cluster_client: "false"
      component: coordinations
      diskSize: 5Gi
      replicas: 1
      resources:
        limits:
          cpu: 500m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 2Gi
      roles: []
    security:
      config:
        adminCredentialsSecret: {}
        adminSecret: {}
        securityConfigSecret: {}
        updateJob:
          resources: {}
      tls:
        http:
          caSecret: {}
          generate: true
          secret: {}
        transport:
          caSecret: {}
          generate: true
          perNode: true
          secret: {}
[...]
```
\
GET _cat/nodes?v
```
ip          heap.percent ram.percent cpu load_1m load_5m load_15m node.role node.roles           cluster_manager name
10.244.2.61           29          70  29    2.71    2.38     2.15 dm        cluster_manager,data -               teste-masters-0
10.244.2.59           42          98  21    2.71    2.38     2.15 m         cluster_manager      *               teste-bootstrap-0
10.244.2.66           27          69  50    2.71    2.38     2.15 dm        cluster_manager,data -               teste-masters-1
10.244.2.64           26          68  21    2.71    2.38     2.15 -         -                    -               teste-coordinations-0
```

**Comment by fpc7063** [comment]
I think the hole empty node.roles equal all roles situation is very misleading (underlying Opensearch/Elastic issue)

**Comment by fpc7063** [comment]
In accordance to the [official docs](https://docs.opensearch.org/docs/latest/tuning-your-cluster/#coordinating-node) shouldn't `"[]"` be a valid [availableRoles](https://github.com/opensearch-project/opensearch-k8s-operator/blob/61fae951a751fa5507a8a8854ca10547ff7c5398/opensearch-operator/pkg/builders/cluster.go#L49)?

**Comment by prudhvigodithi** [comment]
Issue from OpenSearch related to this topic https://github.com/opensearch-project/OpenSearch/issues/3412

**Comment by fpc7063** [comment]
btw @prudhvigodithi, i was playing arround the cluster stat  `GET _cluster/stats` and saw this:
```
"nodes": {
    "count": {
      "total": 7,
      "[]": 1,
      "cluster_manager": 3,
      "coordinating_only": 0,
      "data": 6,
      "ingest": 0,
      "master": 3,
      "remote_cluster_client": 0,
      "search": 0
    }
```
` "[]": 1,`
`"coordinating_only": 0,`
Miscommunication? what's the difference between coordinating_only and []?

**Comment by YeonghyeonKO** [comment]
FYI) Off topic: considering the [release note](https://docs.opensearch.org/docs/latest/breaking-changes/#deprecate-non-inclusive-terms), 
Since "master" role has already been replaced by "cluster_manager", GET _cluster/stats API should be fixed along with @fpc7063 's comment.

**Comment by YeonghyeonKO** [comment]
> btw [@prudhvigodithi](https://github.com/prudhvigodithi), i was playing arround the cluster stat `GET _cluster/stats` and saw this:
> 
> ```
> "nodes": {
>     "count": {
>       "total": 7,
>       "[]": 1,
>       "cluster_manager": 3,
>       "coordinating_only": 0,
>       "data": 6,
>       "ingest": 0,
>       "master": 3,
>       "remote_cluster_client": 0,
>       "search": 0
>     }
> ```
> 
> ` "[]": 1,` `"coordinating_only": 0,` Miscommunication? what's the difference between coordinating_only and []?

@fpc7063 , I just deployed 3.1.0 cluster using docker-compose and ran the command `GET _cluster/stats`, there was no "[]" field in `nodes.count`. Which version do you currently use to test your cluster?

**Comment by prudhvigodithi** [comment]
Yes seeing the docs https://docs.opensearch.org/docs/latest/tuning-your-cluster/, the `node.roles: []` should be coordinating node and `coordinating_only` should be updated. Adding @andrross @reta please correct me if I'm wrong.
@YeonghyeonKO so setting as `node.roles: []` and you dont see  "[]": 1, ?

Thanks

**Comment by andrross** [comment]
@YeonghyeonKO @fpc7063 @prudhvigodithi The node.roles setting can take arbitrary strings. The fact that `"[]": 1` is showing up in node stats suggest that the literal string `"[]"` is being passed into node.roles. I can replicate that by configuring the following value:

```
node.roles: ["[]"]
```

It looks to me like something is getting misconfigured in the yaml. For a coordinator-only node you need to pass an empty list to the yaml setting (e.g. `node.roles: []`).

**Comment by prudhvigodithi** [comment]
Got it, coming from this issue I created in past https://github.com/opensearch-project/OpenSearch/issues/3412#issue-1242493715, I see the error `org.opensearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown role [" "]`. May be we should throw the same arbitrary strings other than for `node.roles: []`.

**Comment by andrross** [comment]
> Got it, coming from this issue I created in past [opensearch-project/OpenSearch#3412 (comment)](https://github.com/opensearch-project/OpenSearch/issues/3412#issue-1242493715), I see the error `org.opensearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown role [" "]`. May be we should throw the same arbitrary strings other than for `node.roles: []`.

@prudhvigodithi Arbitrary strings are a feature as far as I know :) Plugins can use arbitrary role names. I believe ml-commons uses the `ml` role for offloading some compute functions to dedicated nodes.

**Comment by andrross** [comment]
> FYI) Off topic: considering the [release note](https://docs.opensearch.org/docs/latest/breaking-changes/#deprecate-non-inclusive-terms), Since "master" role has already been replaced by "cluster_manager", GET _cluster/stats API should be fixed along with [@fpc7063](https://github.com/fpc7063) 's comment.

@YeonghyeonKO Check out [this issue](https://github.com/opensearch-project/OpenSearch/issues/5214#issuecomment-2660549148). We're still keeping the "master" term in a few places to ease the transition. It will be removed in 4.0.

**Comment by bjolo** [comment]
I have a question about this. Why should coordinator be a special role: [],  when all other roles have explicit names like data, ingest, etc? why not keeping it simple and explicit and have a role: coordinator

**Comment by andrross** [comment]
> I have a question about this. Why should coordinator be a special role: [], when all other roles have explicit names like data, ingest, etc? why not keeping it simple and explicit and have a role: coordinator

Great question. I think the answer is that all nodes are implicitly a coordinator and the way you make a node "not a coordinator" is by not sending HTTP traffic to it. It follows that to make a node "only a coordinator" is to remove all other roles and then send HTTP traffic to it, so the only job it does is the coordinating work.

**Comment by fpc7063** [comment]
> [@YeonghyeonKO](https://github.com/YeonghyeonKO) [@fpc7063](https://github.com/fpc7063) [@prudhvigodithi](https://github.com/prudhvigodithi) The node.roles setting can take arbitrary strings. The fact that `"[]": 1` is showing up in node stats suggest that the literal string `"[]"` is being passed into node.roles. I can replicate that by configuring the following value:
> 
> ```
> node.roles: ["[]"]
> ```
> 
> It looks to me like something is getting misconfigured in the yaml. For a coordinator-only node you need to pass an empty list to the yaml setting (e.g. `node.roles: []`).

Thanks for the input, i'm not setting the node.roles through opensearch.yml. I'm using the environment variable.

Opensearch version: 3.1.0
```yaml
    - name: node.roles
      value: '[]'
```
```json
{
      "total": 7,
      "[]": 1,
      "cluster_manager": 3,
      "coordinating_only": 0,
      "data": 6,
      "ingest": 0,
      "master": 3,
      "remote_cluster_client": 0,
      "search": 0
}
```


I think it might derive from the following, value is already expected to be a list, so putting `[]` is being parsed as `["[]"]` in the end. Example with cluster_manager:
```yaml
        - name: node.roles
          value: cluster_manager,data
```



Since the nomenclature `coordinating_only` is already being used a better more explicit way to set it should be:
(Note: i'm editing the sts directly for testing. Setting up 10 different yamls for the test it's just too much pain)
```yaml
        - name: node.roles
          value: coordinating_only
```

In the end it does count toward the "metric":
```json
"count": {
      "total": 8,
      "cluster_manager": 3,
      "coordinating_only": 1,
      "data": 7,
      "ingest": 0,
      "master": 3,
      "remote_cluster_client": 0,
      "search": 0,
      "warm": 0
    },
```

**Comment by fpc7063** [comment]
> > Got it, coming from this issue I created in past [opensearch-project/OpenSearch#3412 (comment)](https://github.com/opensearch-project/OpenSearch/issues/3412#issue-1242493715), I see the error `org.opensearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown role [" "]`. May be we should throw the same arbitrary strings other than for `node.roles: []`.
> 
> [@prudhvigodithi](https://github.com/prudhvigodithi) Arbitrary strings are a feature as far as I know :) Plugins can use arbitrary role names. I believe ml-commons uses the `ml` role for offloading some compute functions to dedicated nodes.

So in the end the better way is just for the operator to stop validating `node.roles` entirely so any plugin can run on their dedicated nodes without the need for operator specific support

**Comment by bjolo** [comment]
hi again,

Yes, i understand that in opensearch architecture all nodes are implicit coordinators, but that does not restrict the operator from being explicit and consistent in the charts. pseudo code: if role = coordinator then role.node = []

My point is to think about the end users and make the operator as simple and straightforward to use as possible. I had to dig and google quite a bit to even find the role: [] work around. In my opinion it would be simpler and consistent with a defined roles: coordinator

**Comment by prudhvigodithi** [comment]
I dont think there is a restriction from operator side with the role name (Let me double check on this).  Based on @fpc7063 testing here https://github.com/opensearch-project/opensearch-k8s-operator/issues/1023#issuecomment-3066031631 looks like passing `coordinating_only` shows the right behavior, here is a small test I have done.

#### Start the docker container with `coordinating_only`
```
docker run -e "DISABLE_SECURITY_PLUGIN=true" -e "discovery.type=single-node" -e 'node.roles=coordinating_only' opensearchproject/opensearch:3 -p 9200:9200
```

#### Docker logs 
```
[2025-07-14T15:28:13,017][INFO ][o.o.n.Node               ] [9179ec2ba7ba] node name [9179ec2ba7ba], node ID [L5uyQASpQyG5nQvDipmY3g], cluster name [docker-cluster], roles [coordinating_only, cluster_manager]
```

#### Using `curl localhost:9200/_cluster/stats` API.

```
  "nodes": {
    "count": {
      "total": 1,
      "cluster_manager": 1,
      "coordinating_only": 1,
      "data": 0,
      "ingest": 0,
      "master": 1,
      "remote_cluster_client": 0,
      "search": 0,
      "warm": 0
    }
```

So based on this IMO the operator should also support `coordinating_only`
```
      roles:
        - "data"
        - "cluster_manager"
        - "coordinating_only"
```

@bjolo @fpc7063 can you give a try by passing `coordinating_only` to `OpenSearchCluster` CRD?
Thanks 
@rootxrishabh

**Comment by fpc7063** [comment]
I think any role that doest not match one of [these roles](https://github.com/opensearch-project/opensearch-k8s-operator/blob/7fdc6cfa562ce098b0da42c13cc18a9dbd6373ce/opensearch-operator/pkg/builders/cluster.go#L49) does not get propagated into the statefulset.

opensearchclusters.opensearch.opster.io opensearch-cluster
```yaml
[...]
- component: coordinators
      diskSize: 5Gi
      persistence:
        pvc:
          accessModes:
          - ReadWriteOnce
          storageClass: local-path
      replicas: 1
      resources:
        limits:
          cpu: 1500m
          memory: 2Gi
        requests:
          cpu: 1500m
          memory: 2Gi
      roles:
      - coordinating_only
[...]
```

opensearch-cluster-coordinators
```yaml
[...]
        - name: OPENSEARCH_JAVA_OPTS
          value: -Xmx1024M -Xms1024M -Dopensearch.transport.cname_in_publish_address=true
        - name: node.roles
        - name: http.port
          value: "9200"
[...]
```

**Comment by fpc7063** [comment]
No validations on helm chart preventing this.
Chart version: v3.1.0

**Comment by sudosaket** [comment]
They way I got `coordinating_only` nodes to work is add a node pool with the following `additionalConfig`:
```
      additionalConfig:
        node.data: "false"
        node.ingest: "false"
        node.master: "false"
        node.remote_cluster_client: "false"
```
and then specify the roles as an empty list:
```
      roles: [] # dedicated coordinating nodes
```

This is on OS v2.19, but I believe we don't need the additional config properties in v3.X.
