### ISSUE TITLE
[BUG] bootstrap pod is in crashloopbackoff

### ISSUE THREAD

**Issue by joshuacox** [opensearch-project/opensearch-k8s-operator#1026]
### What is the bug?
the bootstrap pod is in crashloopbackoff:

```
example              opensearch-example-bootstrap-0                                    0/1     CrashLoopBackOff   6 (49s ago)   9m12s
```

With the first error being:

```
Enabling OpenSearch Security Plugin
2025-06-12 20:40:35,579 main ERROR Could not reconfigure JMX java.lang.NullPointerException: Cannot invoke "jdk.internal.platform.CgroupInfo.getMountPoint()" because "anyController" is null
```

[full container logs](https://gist.github.com/joshuacox/3891694f7f2ef3260127de10a098c1b3)

### How can one reproduce the bug?

I have a repo that I use to exemplify issues I have with kubernetes in kind on my laptop [here](https://github.com/DeployCoop/vigilant-octo-waffle/)

I installed the opensearch-operator using the helmc chart without changing anything in the values.yaml.

my opensearch-cluster.yaml looks like this:

```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name:  opensearch-example
  namespace: example
spec:
  general:
    serviceName: opensearch-example
    version: "2.3.0"
  dashboards:
    enable: true
    version: "2.3.0"
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: nodes
      replicas: 1
      diskSize: "5Gi"
      nodeSelector:
      resources:
         requests:
            memory: "512Mi"
            cpu: "200m"
         limits:
            memory: "512Mi"
            cpu: "200m"
      roles:
        - "cluster_manager"
        - "data"
```

### What is the expected behavior?
the bootstrap to finish so the other pods can start

### What is your host/environment?
KinD on arch linux

```
uname -a
Linux perseus 6.12.33-1-lts #1 SMP PREEMPT_DYNAMIC Tue, 10 Jun 2025 13:16:59 +0000 x86_64 GNU/Linux
```

### Do you have any screenshots?

Its more of a kubernetes thing so I can supply text like a [description of the pod](https://gist.github.com/joshuacox/274f07cee8bd1a2a1f22f34f04d34297) or more logs like the [logs from the operator pod](https://gist.github.com/joshuacox/3cc88f0d925935503dada9f41dda75b9).

### Do you have any additional context?

I am using [argo](https://github.com/DeployCoop/vigilant-octo-waffle/blob/main/argo/opensearch-operator/argocd.yaml) to install the helm chart.
