### ISSUE TITLE
[BUG] Logic error in ismpolicy regarding the "shrink" action

### ISSUE THREAD

**Issue by vinylen** [opensearch-project/opensearch-k8s-operator#1030]
### What is the bug?
If we try and create a ISM policy which has the action "shrink" and only want to set `numNewShards`, the operator returns an error:

`Exactly one option specifying the number of shards to shrink to must be used.`

If we set the option `maxShardSize` it works but we can't combine the two options, so we are effectively stuck using `maxShardSize`.

### How can one reproduce the bug?
The ISM policy provided below will not work, the operator will return an error like the one mentioned above.

```
---
apiVersion: opensearch.opster.io/v1
kind: OpenSearchISMPolicy
metadata:
   name: prod-del90
spec:
   opensearchCluster:
      name: prod
   description: ISM Policy for test-logs
   ismTemplate:
      priority: 100
      indexPatterns:
        - "test-logs"
   defaultState: hot
   states:
      - name: hot
        actions:
           - rollover:
              minIndexAge: "7d"
              minPrimaryShardSize: "40Gb"
        transitions:
           - stateName: warm
             conditions:
                minIndexAge: "7d"
      - name: warm
        actions:
          - shrink:
              numNewShards: 1
        transitions:
           - stateName: delete
             conditions:
                minIndexAge: "90d"
      - name: delete
        actions:
          - delete: {}

```

If we instead change the shrink action to `maxShardSize: "50gb"` it works:
```
- name: warm
  actions:
    - shrink:
        # numNewShards: 1
        maxShardSize: "50gb"
```

### What is the expected behavior?
The operator should accept setting either `maxShardSize` or `numNewShards`.

### What is your host/environment?
OpenSearch version 3.0.0
Operator version 2.7.0
