### ISSUE TITLE
[FEATURE] Allow bootstrap image to be pulled through a user defined registry

### ISSUE THREAD

**Issue by fpc7063** [opensearch-project/opensearch-k8s-operator#1034]
### Is your feature request related to a problem?
Pulling the bootstrap image directly through docker.io `docker.io/busybox:1.36` is not a option in more locked up environments . The CRD does not currently allow setting the image

### What solution would you like?
Allow setting the full image name through the CRD and then allow it to be set through the helm chart

### What alternatives have you considered?
Not any in the scope of the project itself, OPA policy, editing the Container Runtime Engine configs

**Comment by prudhvigodithi** [comment]
[Triage]
This is a valid ask and I agree we should have user defined registry for bootstrap image. Can you please create a PR with this change @fpc7063 ?
Adding @rootxrishabh

**Comment by fpc7063** [comment]
I still have to learn go, if this is still pending in some months i can do it.
If you need anything in helm or triaging just ping me

**Comment by fpc7063** [comment]
Btw a bit late. But how is the process to be added to the triage team?
Also, do you have any plans for the docs?

**Comment by Crazyigor1987** [comment]
Hi,

well, we've fixed it by adjusting it in the OpenSearchCluster crd.
Something like:

```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch
spec:
  general:
    serviceName: opensearch
    version: 2.19.1
    image: "our.own.registry/dockerio/opensearchproject/opensearch:2.19.1"
    imagePullSecrets:
      - name: registry-proxy
    ...
    ...
    ...
  initHelper:
    image: "our.own.registry/dockerio/busybox:latest"
    imagePullSecrets:
      - name: registry-proxy
    ...
    ...
    ...
```
With this entries + additional operator helm values adjustments, we were able to run opensearch in china environment.
