### ISSUE TITLE
[BUG] Not able to configure self signed cert

### ISSUE THREAD

**Issue by pankajsh9472** [opensearch-project/opensearch-k8s-operator#1035]
❗ Problem Summary
I'm trying to expose OpenSearch Dashboards and the OpenSearch API via NGINX Ingress in EKS. Despite following all TLS-related configurations, I'm consistently receiving a 502 Bad Gateway from the NGINX Ingress Controller.

✅ What I've Tried
Ingress Setup:

Defined Ingress with nginx.ingress.kubernetes.io/backend-protocol: "HTTPS".

Enabled proxy-ssl-verify: "true" and provided proxy-ssl-secret pointing to a valid CA (ca.crt only).

Service Exposure:

Backend OpenSearch and Dashboards services are exposed on ports 9200 and 5601 respectively.

TLS is enabled on both services with valid custom certificates (signed by my own CA).

Ingress TLS:

TLS termination is handled at Ingress with valid tls entries and working certs.

Certificates are mounted via Kubernetes secrets and show no errors.

Debugging Done:

curl -vk https://<service> from the NGINX Ingress pod succeeds with a 302 or 200.

`*   Trying 10.240.170.119:5601...
* Connected to opensearch-cluster-dashboards.opensearch.svc.cluster.local (10.240.170.119) port 5601 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: [NONE]
*  start date: Jun 20 15:01:43 2025 GMT
*  expire date: Jun 30 15:01:43 2026 GMT
*  issuer: CN=Test CA
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* using HTTP/1.1
> GET / HTTP/1.1
> Host: opensearch-cluster-dashboards.opensearch.svc.cluster.local:5601
> User-Agent: curl/7.88.1
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/1.1 302 Found
< location: /app/login?
< osd-name: opensearch-cluster-dashboards
< cache-control: private, no-cache, no-store, must-revalidate
< set-cookie: security_authentication=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:00 GMT; HttpOnly; Path=/
< content-length: 0
< Date: Mon, 23 Jun 2025 09:18:26 GMT
< Connection: keep-alive
< Keep-Alive: timeout=120
<
* Connection #0 to host opensearch-cluster-dashboards.opensearch.svc.cluster.local left intact`
NGINX Ingress still returns 502 Bad Gateway for the same services.

Tried Workarounds:

Disabled proxy-ssl-verify to bypass cert validation – still results in 502.

Switched backend-protocol to HTTP temporarily — works if OpenSearch listens on plain HTTP.

❓ Ask / Expectation
I suspect a possible compatibility or certificate validation issue between OpenSearch and NGINX Ingress when using self-signed certs and proxy-ssl-secret. I’d appreciate clarification on:

Are there known issues when OpenSearch serves TLS with custom certs (non-public CA)?

Is there a recommended way to expose OpenSearch behind Ingress with mutual TLS?

Any known incompatibility with nginx.ingress.kubernetes.io/proxy-ssl-secret or CA validation?

**Comment by fpc7063** [comment]
`Are there known issues when OpenSearch serves TLS with custom certs (non-public CA)?`
Not that i am aware, i do this. Although i'm using openshift router, which supports ssl verification for the connection
`Is there a recommended way to expose OpenSearch behind Ingress with mutual TLS?`
You can use for MTLS cases the [ssl-passthrough on ingress nginx](https://kubernetes.github.io/ingress-nginx/user-guide/tls/#ssl-passthrough).

Be aware that when ending the tls termination on the ingress, mtls isn't possible

**Comment by fpc7063** [comment]
I'll try next week to replicate on ingress nginx, but i'm pretty sure it's just bad conf

**Comment by pankajsh9472** [comment]
Hey just to let you know i used my wildcard certificate now i have public dns and public loadbalance AKS using nginx controller below is the cluster.yaml  and ingress.yaml - 
cluster.yaml - 

`apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
  namespace: opensearch
spec:
  general:
    serviceName: opensearch-cluster
    version: 2.3.0
    setVMMaxMapCount: true
  dashboards:
    enable: true
    version: 2.3.0
    replicas: 1
    nodeSelector:
      opensearchNode: "true"
    tolerations:
      - key: "opensearch"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "200m"
  nodePools:
    - component: nodes
      replicas: 3
      diskSize: "5Gi"
      nodeSelector:
        opensearchNode: "true"
      tolerations:
        - key: "opensearch"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
           memory: "2Gi"
           cpu: "500m"
      roles:
        - "cluster_manager"
        - "data"     `

api-ingress.yaml - 
`apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: opensearch
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api-opensearch.<domain>.com
      secretName: my-tls-secret
  rules:
    - host: api-opensearch.<domain>.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opensearch-cluster
                port:
                  number: 9200
`

dash-ingress.yaml - 

`apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dash-ingress
  namespace: opensearch
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dashboards-opensearch.<domain>.com
      secretName: my-tls-secret
  rules:
    - host: dashboards-opensearch.<domain>.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opensearch-cluster-dashboards
                port:
                  number: 5601`



the dashbords work fine with valid https but on api it throws error 502 - 


troubelshotting - 

I checked below curl commands inside ingress controller 

`nginx@nginx-ingress-controller-fb58d98ff-kf5d9:/$ curl -vk -u admin:admin [https://opensearch-cluster.opensearch.svc.cluster.local:9200](vscode-file://vscode-app/c:/Users/U6074844/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) -H "Host: api-opensearch.<domain>.com"

Trying 10.240.37.52:9200...
Connected to opensearch-cluster.opensearch.svc.cluster.local (10.240.37.52) port 9200 (#0)
ALPN: offers h2,http/1.1
TLSv1.3 (OUT), TLS handshake, Client hello (1):
TLSv1.3 (IN), TLS handshake, Server hello (2):
TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
TLSv1.3 (IN), TLS handshake, Request CERT (13):
TLSv1.3 (IN), TLS handshake, Certificate (11):
TLSv1.3 (IN), TLS handshake, CERT verify (15):
TLSv1.3 (IN), TLS handshake, Finished (20):
TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
TLSv1.3 (OUT), TLS handshake, Certificate (11):
TLSv1.3 (OUT), TLS handshake, Finished (20):
SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
ALPN: server did not agree on a protocol. Uses default.
Server certificate:
subject: OU=opensearch-cluster; CN=opensearch-cluster
start date: Jun 26 17:35:49 2025 GMT
expire date: Jun 26 17:35:49 2026 GMT
issuer: CN=opensearch-cluster
SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
using HTTP/1.x
Server auth using Basic with user 'admin'
GET / HTTP/1.1
Host: api-opensearch.<domain>.com
Authorization: Basic YWRtaW46YWRtaW4=
User-Agent: curl/7.88.1
Accept: /

TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/1.1 200 OK
< content-type: application/json; charset=UTF-8
< content-length: 584
<
{
"name" : "opensearch-cluster-nodes-1",
"cluster_name" : "opensearch-cluster",
"cluster_uuid" : "313Pdj5qRcabYBu-6RJ6vg",
"version" : {
"distribution" : "opensearch",
"number" : "2.3.0",
"build_type" : "tar",
"build_hash" : "6f6e84ebc54af31a976f53af36a5c69d474a5140",
"build_date" : "2022-09-09T00:07:12.137133581Z",
"build_snapshot" : false,
"lucene_version" : "9.3.0",
"minimum_wire_compatibility_version" : "7.10.0",
"minimum_index_compatibility_version" : "7.0.0"
},
"tagline" : "The OpenSearch Project: [https://opensearch.org/](vscode-file://vscode-app/c:/Users/U6074844/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)"
}
Connection #0 to host opensearch-cluster.opensearch.svc.cluster.local left intact`

but from local i get - 

`$  curl -vk -u admin:admin https://api-opensearch.<domain>.com
* processing: https://api-opensearch.<domain>.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 128.251.246.215:443...
* Connected to api-opensearch.<domain>.com (128.251.246.215) port 443
* schannel: disabled automatic use of client certificate
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* using HTTP/1.x
* Server auth using Basic with user 'admin'
> GET / HTTP/1.1
> Host: api-opensearch.<domain>.com
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/8.2.1
> Accept: */*
>
< HTTP/1.1 502 Bad Gateway
< Server: nginx/1.27.4
< Date: Thu, 26 Jun 2025 18:28:44 GMT
< Content-Type: text/html
< Content-Length: 157
< Connection: keep-alive
<
{ [157 bytes data]
100   157  100   157    0     0    176      0 --:--:-- --:--:-- --:--:--   177<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.27.4</center>
</body>
</html>

* Connection #0 to host api-opensearch.<domain>.com left intact
`


`

**Comment by fpc7063** [comment]
Sorry, can you reformat the yamls you sent, using triple grave
\`\`\`yaml
apiVersion: v1
\`\`\`
```yaml
apiVersion: v1
```

**Comment by fpc7063** [comment]
Couldn't make sense of the requests you sent here, could you wrap those on triple grave (`) also?

`but from local i get -`
Do you mean your own machine or the pod?

**Comment by fpc7063** [comment]
`Authorization: Basic YWRtaW46YWRtaW4=`
Also, just making sure this isn't a public facing server because you sent the header here and it's default user and password

**Comment by pankajsh9472** [comment]
I am using below -

cluster.yaml - 

```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
  namespace: opensearch
spec:
  security:
    tls:
      transport:
        generate: true
        perNode: false
      http:
        generate: true
  general:
    serviceName: opensearch-cluster
    version: 2.3.0
    setVMMaxMapCount: true
  dashboards:
    enable: true
    version: 2.3.0
    replicas: 1
    nodeSelector:
      opensearchNode: "true"
    tolerations:
      - key: "opensearch"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "200m"
  nodePools:
    - component: nodes
      replicas: 3
      diskSize: "5Gi"
      nodeSelector:
        opensearchNode: "true"
      tolerations:
        - key: "opensearch"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
           memory: "2Gi"
           cpu: "500m"
      roles:
        - "cluster_manager"
        - "data"     
```
api-ingress.yaml - 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: opensearch
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api-opensearch.X.com
      secretName: my-tls-secret
  rules:
    - host: api-opensearch.X.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: opensearch-cluster
                port:
                  number: 9200 
```
				  
				  
getting 502 on the nginx - 

troubleshoting fron nginx controller pod - 

`curl -v https://opensearch-cluster.opensearch.svc.cluster.local:9200`

```
*   Trying 10.240.79.156:9200...
* Connected to opensearch-cluster.opensearch.svc.cluster.local (10.240.79.156) port 9200 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
