### ISSUE TITLE
[FEATURE] set annotations for PVC

### ISSUE THREAD

**Issue by dvtpei** [opensearch-project/opensearch-k8s-operator#1036]
### Is your feature request related to a problem?
I need annotations on the PVCs of my opensearch cluster e.g. a cost center annotation.

### What solution would you like?
Allow to set annotations on

```YAML
- component: nodes
      annotations:
        my/annotation: abc
      persistence:
        pvc:
          # allow to set annotations here
          annotations:
            my/annotation: abc
          storageClass: 
          accessModes:
            - ReadWriteOnce
```

### What alternatives have you considered?
* creating the PVCs manually and try to attach with operator
* add annotations after operator has created them
