### ISSUE TITLE
[BUG] initHelper setting of values.yaml in opensearch-cluster-3.1.0

### ISSUE THREAD

**Issue by YeonghyeonKO** [opensearch-project/opensearch-k8s-operator#1039]
### What is the bug?
```yaml
  dashboards:
    {{- omit . "image" | toYaml | nindent 4 }}
    image: {{ .image }}:{{ .version }}
  {{- end }}
  {{- with .Values.cluster.general }}
  general:
    {{- omit . "image" "serviceName" | toYaml | nindent 4 }}
    image: {{ .image }}:{{ .version }}
    serviceName: {{ .serviceName | default $clusterName }}
  {{- end }}
  {{- with .Values.cluster.initHelper }}
  initHelper: {{ . | toYaml | nindent 4 }}
  {{- end }}
```

Since `spec.initHelper` doesn't custom `image` field with `version`, (that is different from `spec.dashboards` and `spec.general`), we cannot use [opensearch-cluster-3.1.0/values.yaml](https://github.com/opensearch-project/opensearch-k8s-operator/blob/opensearch-cluster-3.1.0/charts/opensearch-cluster/values.yaml#L228-L238) chart:
```
  # initHelper configuration
  initHelper:
    # -- initHelper image pull policy
    imagePullPolicy: "IfNotPresent"

    # -- initHelper image pull secret
    imagePullSecrets: []

    # -- initHelper pod cpu and memory resources
    resources: {}

    # -- initHelper version
    version: "1.36"
```
