### ISSUE TITLE
Support adding CSI based volumes to pods

### ISSUE THREAD

**Issue by anubisg1** [opensearch-project/opensearch-k8s-operator#275]
in azure, in order to load secrets from the keyvault the following volume + volumemounts are required:

```
    spec:
      containers:
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-vault"
```

additional volumes are supported according to the documentation  - https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/userguide/main.md  but only limted to configmaps and secrets
