### ISSUE TITLE
[enhancement] - rework how security configuration is passed to the cluster

### ISSUE THREAD

**Issue by anubisg1** [opensearch-project/opensearch-k8s-operator#284]
Today when default configuration needs to be overwritten, then following is used in the manifest:

```
  security:
    config:
      securityConfigSecret:
##Pre create this secret with required security configs, to override the default settings
       name: securityconfig-secret
```

most of the content of the secret though isn't actually a secret but instead it's more suitable to be a configmap.

**The enhancement askes for the following.**

1. ensure that opensearch can understand most (or all) setting values as env variables
2. Move most of the content of securityconfig-secret to an external configmap
3. place into a secret the actual sensitive information such as passwords so that a secret follows the appropriate format of having only key value pairs
4. load the secret values as env-variables in the pod

**Benefits**

1. Complies with the intended use of secrets
2. enables the use of secret keyvaults like 
3. addresses issues like what's described in https://github.com/Opster/opensearch-k8s-operator/issues/235 
4. allows for storing in clear text of opensearch ocnfiguration when leveraging infrastructure as a code
