### ISSUE TITLE
Bootstrap pod does not install plugins from the general spec, fails if plugin specific settings are configured in opensearch.yml

### ISSUE THREAD

**Issue by dobharweim** [opensearch-project/opensearch-k8s-operator#430]
### Description
If I want to provide an S3 API backed repository for opensearch snapshots, but not use S3 itself, I need to provide the `s3.client.default.endpoint` configuration. However this causes the bootstrap pod to fail as it doesn't have the plugin installed and does not recognise the setting.

### Steps to reproduce
1. Install the latest version of the operator.
2. Deploy the following YAML:
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-first-cluster
spec:
  security:
    tls:
       http:
         generate: true 
       transport:
         generate: true
         perNode: true
  general:
    httpPort: 9200
    serviceName: my-first-cluster
    version: 2.3.0
    pluginsList: ["repository-s3"]
    drainDataNodes: true
    additionalConfig:
      s3.client.default.endpoint: "example.s3.com"
  dashboards:
    tls:
      enable: true
      generate: true
    version: 2.3.0
    enable: true
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: masters
      replicas: 3
      resources:
         requests:
            memory: "4Gi"
            cpu: "1000m"
         limits:
            memory: "4Gi"
            cpu: "1000m"
      roles:
        - "data"
        - "cluster_manager"
      persistence:
         emptyDir: {}
```

### Expected Outcome
I expect the bootstrap pod to also install all required plugins so that it can verify the additional config settings.

### Actual outcome
Bootstrap pod fails with the following error:

```[2023-02-12T11:27:04,748][DEPRECATION][o.o.d.c.s.Settings       ] [development-bootstrap-0] [cluster.initial_master_nodes] setting was deprecated in OpenSearch and will be removed in a future release! See the breaking changes documentation for the next major version.
[2023-02-12T11:27:04,774][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [development-bootstrap-0] uncaught exception in thread [main]
org.opensearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [s3.client.default.endpoint] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:184) ~[opensearch-2.5.0.jar:2.5.0]
        at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171) ~[opensearch-2.5.0.jar:2.5.0]
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) ~[opensearch-2.5.0.jar:2.5.0]
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-2.5.0.jar:2.5.0]
        at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-2.5.0.jar:2.5.0]
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137) ~[opensearch-2.5.0.jar:2.5.0]
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103) ~[opensearch-2.5.0.jar:2.5.0]
Caused by: java.lang.IllegalArgumentException: unknown setting [s3.client.default.endpoint] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
        at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:608) ~[opensearch-2.5.0.jar:2.5.0]
        at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:549) ~[opensearch-2.5.0.jar:2.5.0]
uncaught exception in thread [main]
        at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:519) ~[opensearch-2.5.0.jar:2.5.0]
        at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:489) ~[opensearch-2.5.0.jar:2.5.0]
        at org.opensearch.common.settings.SettingsModule.<init>(SettingsModule.java:170) ~[opensearch-2.5.0.jar:2.5.0]
        at org.opensearch.node.Node.<init>(Node.java:506) ~[opensearch-2.5.0.jar:2.5.0]
        at org.opensearch.node.Node.<init>(Node.java:356) ~[opensearch-2.5.0.jar:2.5.0]
        at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.5.0.jar:2.5.0]
        at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.5.0.jar:2.5.0]
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) ~[opensearch-2.5.0.jar:2.5.0]
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) ~[opensearch-2.5.0.jar:2.5.0]
        ... 6 more
java.lang.IllegalArgumentException: unknown setting [s3.client.default.endpoint] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
        at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:608)
        at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:549)
        at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:519)
        at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:489)
        at org.opensearch.common.settings.SettingsModule.<init>(SettingsModule.java:170)
        at org.opensearch.node.Node.<init>(Node.java:506)
        at org.opensearch.node.Node.<init>(Node.java:356)
        at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242)
        at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242)
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404)
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180)
        at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171)
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
        at org.opensearch.cli.Command.main(Command.java:101)
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137)
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103)```
