### ISSUE TITLE
[BUG] OpenSearch Dashboards can't connect to OpenSearch with custom user

### ISSUE THREAD

**Issue by oleksii-kalinin** [opensearch-project/opensearch-k8s-operator#675]
### What is the bug?
The Opensearch dashboard cannot connect to opensearch with a custom user created with securityconfig internal_users approach.

https://github.com/opensearch-project/opensearch-k8s-operator/blob/main/docs/userguide/main.md#custom-admin-user

### How can one reproduce the bug?
<details>

password used in the examples: `LZSZcx8orRHWng6`

<summary>yaml manifests used</summary>

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: securityconfig-secret
type: Opaque
stringData:
...
      internal_users.yml: |-
        _meta:
          type: "internalusers"
          config_version: 2
        admin:
          hash: "$2a$12$mkaUhJrSqKhLI34lTb3PVOQSWWPxxng5A7zbrSgPhOkugJeSKW1FO"
          reserved: true
          backend_roles:
          - "admin"
          description: "Demo admin user"
        dashboarduser:
          hash: "$2y$12$GpoSF/qU9VWZJfB.Rd12dOuRjdNtTdXxP8rs7r2XEVQSVVUxeE1uO"
          reserved: true
          description: "Demo OpenSearch Dashboards user"
....
```

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: os-connections-creds
data:
  username: YWRtaW4K
  password: TFpTWmN4OG9yUkhXbmc2Cg==
---
apiVersion: v1
kind: Secret
metadata:
  name: osd-credentials
data:
  username: ZGFzaGJvYXJkdXNlcgo=
  password: TFpTWmN4OG9yUkhXbmc2Cg==
```

```yaml
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
spec:
  general:
  ...
  security:
    config:
      adminCredentialsSecret:
        # For operator auth to the OS cluster
        name: os-connections-creds
      securityConfigSecret:
       ##Pre create this secret with required security configs, to override the default settings
       name: securityconfig-secret
  ...
  dashboards:
  ...
    opensearchCredentialsSecret:
      name: osd-credentials
```
</details>

<details>
<summary>testing</summary>

```
$ curl -u dashboarduser:LZSZcx8orRHWng6 -sk https://localhost:9200/_plugins/_security/api/account?pretty
{
  "user_name" : "dashboarduser",
...
}
```

```
$ curl -u admin:LZSZcx8orRHWng6 -sk https://localhost:9200/_plugins/_security/api/account?pretty
{
  "user_name" : "admin",
...
}
```

</details>

<details>

<summary>logs</summary>

OS

```
{"type":"log","@timestamp":"2023-12-05T10:20:53Z","tags":["error","opensearch","data"],"pid":1,"message":"[ResponseError]: Response Error"}
{"type":"log","@timestamp":"2023-12-05T10:20:56Z","tags":["error","opensearch","data"],"pid":1,"message":"[ResponseError]: Response Error"}
{"type":"log","@timestamp":"2023-12-05T10:20:58Z","tags":["error","opensearch","data"],"pid":1,"message":"[ResponseError]: Response Error"}
{"type":"log","@timestamp":"2023-12-05T10:21:01Z","tags":["error","opensearch","data"],"pid":1,"message":"[ResponseError]: Response Error"}
{"type":"log","@timestamp":"2023-12-05T10:21:03Z","tags":["error","opensearch","data"],"pid":1,"message":"[ResponseError]: Response Error"}
{"type":"log","@timestamp":"2023-12-05T10:21:06Z","tags":["error","opensearch","data"],"pid":1,"message":"[ResponseError]: Response Error"}
{"type":"log","@timestamp":"2023-12-05T10:21:08Z","tags":["error","opensearch","data"],"pid":1,"message":"[ResponseError]: Response Error"}
{"type":"log","@timestamp":"2023-12-05T10:21:11Z","tags":["error","opensearch","data"],"pid":1,"message":"[ResponseError]: Response Error"}
{"type":"log","@timestamp":"2023-12-05T10:21:13Z","tags":["error","opensearch","data"],"pid":1,"message":"[ResponseError]: Response Error"}
```

OSD

```
[2023-12-05T10:01:01,537][WARN ][o.o.s.a.BackendRegistry  ] [opensearch-cluster-hot-0] Authentication finally failed for dashboarduser
 from 10.1.5.77:44828
[2023-12-05T10:01:04,042][WARN ][o.o.s.a.BackendRegistry  ] [opensearch-cluster-hot-0] Authentication finally failed for dashboarduser
 from 10.1.5.77:44828
```
</details>

### What is the expected behavior?
OSD can connect to the OS with custom user/password

### What is your host/environment?
Docker, OS/OSD 2.8.0
Operator 2.4.0 (main)

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
```
{"level":"error","ts":"2023-12-05T09:54:27.801Z","msg":"Reconciler error","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchCluster":{"name":"opensearch-cluster","namespace":"elastic-stack-logging"},"namespace":"elastic-stack-logging","name":"opensearch-cluster","reconcileID":"6a677a6f-c025-44e8-bae6-6149fd99f92d","error":"invalid character 'U' looking for beginning of value","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226"}
{"level":"error","ts":"2023-12-05T10:04:28.719Z","msg":"Reconciler error","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchCluster":{"name":"opensearch-cluster","namespace":"elastic-stack-logging"},"namespace":"elastic-stack-logging","name":"opensearch-cluster","reconcileID":"490e86db-22f9-49dd-b7ea-7f9778b2a960","error":"invalid character 'U' looking for beginning of value","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226"}
```
