### ISSUE TITLE
[BUG] Cannot create coordinating nodes

### ISSUE THREAD

**Issue by flavienbwk** [opensearch-project/opensearch-k8s-operator#697]
### What is the bug?

I get the following error when assigning no role to a node.

```
Error: UPGRADE FAILED: cannot patch "opensearch-cluster" with kind OpenSearchCluster: OpenSearchCluster.opensearch.opster.io "opensearch-cluster" is invalid: spec.nodePools[1].roles: Required value
```

But this is [a valid value for an OpenSearch cluster](https://forum.opensearch.org/t/how-to-allocate-coordinating-node-role/14784/2?u=janstack) for a node to act as a client/coordinating node.

### How can one reproduce the bug?

Helm configuration:

```yaml
opensearchCluster:
  enabled: true
  general:
    httpPort: "9200"
    version: 2.11.0
    serviceName: "opensearch-cluster"
    drainDataNodes: true
    setVMMaxMapCount: true
  nodePools:
    - component: masters
      diskSize: "20Gi"
      replicas: 3
      roles:
        - "master"
        - "data"
      resources:
        requests:
          memory: "4Gi"
          cpu: "2000m"
        limits:
          memory: "4Gi"
          cpu: "2000m"
    - component: clients
      diskSize: "20Gi"
      replicas: 3
      roles: []
      resources:
        requests:
          memory: "4Gi"
          cpu: "2000m"
        limits:
          memory: "4Gi"
          cpu: "2000m"
  security:
    tls:
      transport:
        generate: true
      http:
        generate: true
```

### What is the expected behavior?

Set an empty array of roles for the node when setting `roles: []`.

### What is your host/environment?

Ubuntu 22.04 with Kubernetes 1.28.2.
