### ISSUE TITLE
[BUG] Node pool and Dashboard pod affinity settings are not taken into account when deploying via Helm

### ISSUE THREAD

**Issue by dmantas** [opensearch-project/opensearch-k8s-operator#699]
### What is the bug?
When deploying a cluster via Helm chart, defining `affinity` under `dashboards` or under one of the `nodePools` is not taken into account. Checking the Dashboards Deployment or the Node Pool StatefulSet shows that the pods do not have any affinity settings at all.

If the cluster is deployed by using `kubectl apply` on the `OpenSearchCluster` manifest, affinity is applied to the pods.

### How can one reproduce the bug?
Create a `values.yaml` file where under `nodePools:` the following exists:

```
    - component: data-nodes
      diskSize: "5Gi"
      replicas: 3
      roles:
        - "data"
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "500m"
    - component: cluster-managers
      diskSize: "1Gi"
      replicas: 3
      roles:
        - "cluster_manager"
      resources:
        limits:
          memory: "2Gi"
          cpu: "500m"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "opster.io/opensearch-nodepool"
                    operator: In
                    values:
                      - "cluster-managers"
              topologyKey: "kubernetes.io/hostname"
```

### What is the expected behavior?
When checking the `cluster-managers` StatefulSet definition:

```
 k get statefulset.apps/caas-opensearch-cluster-managers -o yaml   
```

we expect to see the affinity settings:

```
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: opster.io/opensearch-nodepool
                operator: In
                values:
                - cluster-managers
            topologyKey: kubernetes.io/hostname
```

However, there is no `affinity` key at all under `spec`.

### What is your host/environment?
Opensearch k8s operator version: 2.4.0
Opensearch version: 2.8.0
