### ISSUE TITLE
Back-off pulling image "public.ecr.aws/opsterio/opensearch-operator:2.3.1"[BUG]

### ISSUE THREAD

**Issue by vkumar85** [opensearch-project/opensearch-k8s-operator#709]
### What is the bug?
_A clear and concise description of the bug._

Did anything change with the location of this image reccently?

### How can one reproduce the bug?
_Steps to reproduce the behavior._

I am just trying to redeploy the helm chart.

### What is the expected behavior?
_A clear and concise description of what you expected to happen._

Image pull should be successful.

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

![image](https://github.com/opensearch-project/opensearch-k8s-operator/assets/40867872/4ce98ee4-b78c-4cec-bb71-4b299d32c511)

### Do you have any additional context?
_Add any other context about the problem._

**Comment by pomyslowynick** [comment]
Looks like the ECR is down for it https://gallery.ecr.aws/opsterio/opensearch-operator

**Comment by Rockawear** [comment]
Seeing the same issues as well. it seems like this is Opster repository, do we know if OpenSearch has it's own repo with this image?

**Comment by evheniyt** [comment]
Looks like no, it is still not there https://hub.docker.com/u/opensearchproject
The task regarding the transfer is not resolved https://github.com/opensearch-project/opensearch-k8s-operator/issues/674

**Comment by mustafaonure** [comment]
Seeing the same issues as well. Is there any solution for this issue? anyone know?

**Comment by swoehrl-mw** [comment]
If you can use version 2.4.0 (older images were not mirrored) you can get the image from the compatible MaibornWolff fork of the operator (https://github.com/MaibornWolff/opensearch-operator, ghcr.io/maibornwolff/opensearch-operator:2.4.0). Note that you will have to override image.tag and image.repository in the helm chart values as these still point to the ecr repo. The fork also already has a version 2.5.0 release.

**Comment by swoehrl-mw** [comment]
> Here is also a working fork https://github.com/eliatra/opensearch-k8s-operator from Eliatra

That is incompatible because Eliatra renamed all CRD apigroups.

**Comment by rybnico** [comment]
I found `public.ecr.aws/opsterio/opensearch-operator:2.4.0` on one of my nodes, retagged it and pushed it to `docker.io/nrybnikar/opensearch-operator:2.4.0`. Feel free to use this identical image until this issue is solved. Maybe I can save someone's weekend :)

**Comment by prudhvigodithi** [comment]
Hey I dint expect the opster ECR repo to go down, I will be doing a quick release `2.5.0` release through `opensearch-project/opensearch-k8s-operator` with images pushed to opensearch-project docker and ECR accounts  , this will also include revert of the [PR](https://github.com/opensearch-project/opensearch-k8s-operator/pull/698) that was pushed recently to refactor opster API's.
Tagging @swoehrl-mw, moving forward we can have a community meeting to discuss on next action items with the operator roadmap and if required we can backfill the past releases to opensearch-project docker and ECR accounts.
Thanks
@bbarani @peterzhuamazon

**Comment by jashandeep-sohi** [comment]
Consider also pushing/back-filling images to ghcr.io.

Here's a manually triggered workflow I'm using:

```yaml
name: Backfill Container Image
run-name: ${{ inputs.tag }}
concurrency: ${{ inputs.tag }}

on:
 workflow_dispatch:
   inputs:
     tag:
        description: "Tag to checkout and build"
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/tags/${{ inputs.tag }}
          fetch-tags: true
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: docker/metadata-action@v5
        id: meta
        with:
          context: git
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: opensearch-operator
          push: true
          platforms: linux/amd64,linux/arm,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

**Comment by roskee** [comment]
Any updates on this? I depended on the `public.ecr.aws/opsterio/opensearch-operator:2.4.0` image. If there are any official alternatives, I would be more than happy to update :pray:

**Comment by BobakMariusz** [comment]
+1 Also facing same problem : public.ecr.aws/opsterio/opensearch-operator:2.4.0

**Comment by sunsrin** [comment]
Tried with :latest which was uploaded 2 hours back (2.3.2) .. but the controller manager seems to be failing health check (might be unrelated) or my environment issue

**Comment by prudhvigodithi** [comment]
Hey Everyone, a quick update, at this point we are still working with opensearch-project opensource team to get some approvals to publish the images to opensearch-project dockerHub and ECR registries.
https://gallery.ecr.aws/opensearchproject/ 
https://hub.docker.com/u/opensearchproject 
Thank you

**Comment by agershman** [comment]
> Hey Everyone, a quick update, at this point we are still working with opensearch-project opensource team to get some approvals to publish the images to opensearch-project dockerHub and ECR registries. https://gallery.ecr.aws/opensearchproject/ https://hub.docker.com/u/opensearchproject Thank you

@prudhvigodithi This may be a known issue but I'm observing that multi-arch builds don't seem to be in place. E.g. I can pull a version the operator image but only `linux/amd64` platform images appear to be available. This is problematic for cases where the underlying platform is `linux/arm64`.

**Comment by prudhvigodithi** [comment]
Hey @agershman, the operator project is recently migrated to [opensearch-project](https://github.com/opensearch-project/) org, so we are working on publishing the images to following registries:

ECR: https://gallery.ecr.aws/opensearchproject/
Docker: https://hub.docker.com/u/opensearchproject 

Once I got the approval I will go ahead and pushing the images and notify here.

**Comment by prudhvigodithi** [comment]
Hey @jashandeep-sohi thanks, this is more than additional permissions/token setup etc, since now this project is part of the [opensearch-project](https://github.com/opensearch-project/) org, working with the opensource legal team to make sure the package licenses and images published are with open source licenses and are compliant.
Thanks

**Comment by mrvdcsg** [comment]
I didn't see a comment on this thread yet but it appears that opster put 2 images back up on the ECR which resolved our issue (temporarily at least). If you are using 2.4.0 or 2.3.2, the images should pull successfully from https://gallery.ecr.aws/opsterio/opensearch-operator It is fair to say this is only a short-term work-around and they likely put it back up due to all the issues taking it down caused.

**Comment by prudhvigodithi** [comment]
Released `2.5.0` version, the operator images now are part of official OpenSearch Project DockerHub and ECR registries. 
https://gallery.ecr.aws/opensearchproject/opensearch-operator   
https://hub.docker.com/r/opensearchproject/opensearch-operator/tags 

Release build link: https://build.ci.opensearch.org/job/opensearch-operator-release/ 

Please test with `opensearchproject/opensearch-operator:2.5.0` or `public.ecr.aws/opensearchproject/opensearch-operator:2.5.0` and let me know if you see any issues.

Thanks 
@bbarani @swoehrl-mw @peterzhuamazon

**Comment by prudhvigodithi** [comment]
There is a small bug with helm charts for `2.5.0`, I have raised a [PR](https://github.com/opensearch-project/opensearch-k8s-operator/pull/716) to fix and release a small `2.5.1`, but override the bug with `2.5.0` please run:
```
helm install my-opensearch-operator opensearch-operator/opensearch-operator --version 2.5.0 --set manager.image.repository=opensearchproject/opensearch-operator  --set manager.image.tag=2.5.0
```

Thanks you

**Comment by prudhvigodithi** [comment]
Hey Everyone `2.5.1` is released. Please start using `2.5.1`.
```
helm install my-opensearch-operator opensearch-operator/opensearch-operator --version 2.5.1
```

Thank you 

@mrvdcsg @jashandeep-sohi @rybnico @vkumar85 @sunsrin @welkson @vipinjn24 @pomyslowynick @Rockawear @evheniyt @mustafaonure @swoehrl-mw @bbarani

**Comment by welkson** [comment]
@prudhvigodithi 2.5.1 version change API version?

```
k apply -f cluster-dev.yaml
Error from server (NotFound): error when creating "cluster-dev.yaml": the server could not find the requested resource (post opensearchclusters.opensearch.opster.io)
```

manifest file:

```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: test-opensearch-dev
  namespace: test-opensearch-dev
spec:
  general:
    setVMMaxMapCount: true
    serviceName: opensearch-dev
    version: 2.11.1
    # monitoring: 
    #   enable: true 
    #   scrapeInterval: 30s 
    #   monitoringUserSecret: admin-credentials-secret # Optional, name of a secret with username/password for prometheus to acces the plugin metrics endpoint with, defaults to the admin user
    #   pluginUrl: https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.8.0.0/prometheus-exporter-2.8.0.0.zip
    # pluginsList: ["https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.8.0.0/prometheus-exporter-2.8.0.0.zip"]
  security:
    config:
      securityConfigSecret:
        name: securityconfig-secret
      adminCredentialsSecret:
        name: admin-credentials-secret
    tls:
       http:
         generate: true 
       transport:
         generate: true
         perNode: true    
  confMgmt:
    smartScaler: true
  dashboards:
    enable: true
    version: 2.11.1
    replicas: 1
    opensearchCredentialsSecret:
      name: admin-credentials-secret
    resources:
      requests:
          memory: "5Mi"
          cpu: "1m"
      limits:
          memory: "1Gi"
          cpu: "4"
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "30Gi"
      jvm: -Xmx1024M -Xms1024M
      nodeSelector:
      resources:
          requests:
            memory: "2Gi"
            cpu: "2"
          limits:
            memory: "6Gi"
            cpu: "4"
      roles:
        - "cluster_manager"
      persistence:
        pvc:
          accessModes:
          - ReadWriteOnce
          storageClass: default-storageclass
    - component: data
      replicas: 3
      diskSize: "100Gi"
      jvm: -Xmx1024M -Xms1024M
      nodeSelector:
      resources:
          requests:
            memory: "2Gi"
            cpu: "2"
          limits:
            memory: "6Gi"
            cpu: "4"
      roles:
        - "data"
        - "ingest"
      persistence:
        pvc:
          accessModes:
          - ReadWriteOnce
          storageClass: default-storageclass
    - component: coordinating
      replicas: 1
      diskSize: "54Gi"
      jvm: -Xmx1024M -Xms1024M
      nodeSelector:
      resources:
          requests:
            memory: "2Gi"
            cpu: "2"
          limits:
            memory: "6Gi"
            cpu: "4"
      roles:
        - ""
      additionalConfig:
        node.master: "false"
        node.data: "false"
        node.ingest: "false"
        node.remote_cluster_client: "false"
      persistence:
        pvc:
          accessModes:
          - ReadWriteOnce
          storageClass: default-storageclass
```

**Comment by agershman** [comment]
@prudhvigodithi I wanted to circle back on my earlier comment. I'm seeing that the reestablished helm chart and referenced image at version `2.5.1` does indeed include multi-arch support (e.g. `linux/amd64` and `linux/arm64`). What I am however not seeing is that previous existing versions (e.g. `2.4.0`) do not include much-arch support (i.e. only `linux/amd64` appears to be back in place). This forces folks who were using/pinned on `2.4.0` to upgrade to `2.5.1`. Is this expected or is there still ongoing work to get multi-arch builds retroactively created for versions `< 2.5.1`?

**Comment by prudhvigodithi** [comment]
Hey @welkson, there is no change in API's
```
helm install my-opensearch-operator opensearch-operator/opensearch-operator --version 2.5.1
NAME: my-opensearch-operator
LAST DEPLOYED: Sat Feb  3 10:30:17 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None

k get crd | grep -i "opensearchclusters.opensearch.opster.io"
opensearchclusters.opensearch.opster.io             2024-02-03T18:30:32Z

```

**Comment by prudhvigodithi** [comment]
> @prudhvigodithi I wanted to circle back on my earlier comment. I'm seeing that the reestablished helm chart and referenced image at version `2.5.1` does indeed include multi-arch support (e.g. `linux/amd64` and `linux/arm64`). What I am however not seeing is that previous existing versions (e.g. `2.4.0`) do not include much-arch support (i.e. only `linux/amd64` appears to be back in place). This forces folks who were using/pinned on `2.4.0` to upgrade to `2.5.1`. Is this expected or is there still ongoing work to get multi-arch builds retroactively created for versions `< 2.5.1`?

Hey @agershman, is it something stopping for the operator upgrade to 2.5.1? After the repo was migrated to the opensearch-project org it was unexpected the old images are removed from ECR, so at this point might need to get approvals for all the backfill versions (for all versions <2.5.0).
Adding @bbarani

**Comment by agershman** [comment]
> > @prudhvigodithi I wanted to circle back on my earlier comment. I'm seeing that the reestablished helm chart and referenced image at version `2.5.1` does indeed include multi-arch support (e.g. `linux/amd64` and `linux/arm64`). What I am however not seeing is that previous existing versions (e.g. `2.4.0`) do not include much-arch support (i.e. only `linux/amd64` appears to be back in place). This forces folks who were using/pinned on `2.4.0` to upgrade to `2.5.1`. Is this expected or is there still ongoing work to get multi-arch builds retroactively created for versions `< 2.5.1`?
> 
> Hey @agershman, is it something stopping for the operator upgrade to 2.5.1? After the repo was migrated to the opensearch-project org it was unexpected the old images are removed from ECR, so at this point might need to get approvals for all the backfill versions (for all versions <2.5.0). Adding @bbarani

Nothing stopping us given the changes in `2.5.0` and `2.5.1` being non-functional. Just was curious if it was expected that versions prior to `2.5.1` would be back but not include multi-arch support. Our path forward will have to be bump to `2.5.1` which again is fine given the diff.

**Comment by prudhvigodithi** [comment]
Just to add @welkson, the following are steps I have tried and looks green, can you please check ?

1. Install 2.5.0 

```
helm install opensearch-operator opensearch-operator/opensearch-operator --version 2.5.0 --set manager.image.repository=opensearchproject/opensearch-operator  --set manager.image.tag=2.5.0
```

2. Apply the manifest file

```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: pgcluster
  namespace: default
spec:
  security:
    config: 
    tls:
       http:
         generate: true 
       transport:
         generate: true
         perNode: true
  general:
    httpPort: 9400
    serviceName: my-first-cluster
    version: 2.11.0
    pluginsList: ["https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.11.0.0/prometheus-exporter-2.11.0.0.zip"]
    drainDataNodes: true
  dashboards:
    version: 2.11.0
    enable: true
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: masters
      replicas: 3
      additionalConfig:
        path.repo: '["/tmp/snapshots"]'
      resources:
         requests:
            memory: "1Gi"
            cpu: "550m"
         limits:
            memory: "1Gi"
            cpu: "550m"
      roles:
        - "data"
        - "cluster_manager"
      persistence:
         emptyDir: {}
```

3. Upgrade the operator to 2.5.1

```
helm upgrade opensearch-operator opensearch-operator/opensearch-operator --version 2.5.1 --set manager.image.repository=opensearchproject/opensearch-operator  --set manager.image.tag=2.5.1


helm ls 
NAME               	NAMESPACE	REVISION	UPDATED                           	STATUS  	CHART                    	APP VERSION
opensearch-operator	default  	2       	2024-02-03 10:43:33.3483 -0800 PST	deployed	opensearch-operator-2.5.1	2.5.1     
```
4. Re-apply the manifest file.

```
k apply -f cluster.yaml 
opensearchcluster.opensearch.opster.io/pgcluster unchanged
```
