### ISSUE TITLE
[BUG] Increased diskSize is not reflected in the pods filesystem 

### ISSUE THREAD

**Issue by dmantas** [opensearch-project/opensearch-k8s-operator#723]
### What is the bug?
When we increase `diskSize` in the `OpensearchCluster` spec, the PVCs are resized accordingly. However, filesystem in the pods is not resized. Or, to be precise, it _might_ be resized for _some_ of the pods.

We use Openstack with Cinder volume (Storage class: `csi-cinder-sc-delete`).

### How can one reproduce the bug?
In an already deployed cluster with `diskSize` for a nodePool equal to `5Gi`, modify `diskSize` and increase it to `6Gi`. Then apply the manifest.
Then increase it to `7Gi` and apply the manifest again. So the `nodePools` config looks like

```
    nodePools:
    - affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: opster.io/opensearch-nodepool
                operator: In
                values:
                - data-nodes
            topologyKey: kubernetes.io/hostname
      component: data-nodes
      diskSize: 7Gi
      replicas: 3
      resources:
        limits:
          cpu: 500m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 2Gi
      roles:
      - data
````

Check the PVCs, they are `7Gi` in size:

```
data-caas-opensearch-data-nodes-0         Bound    pvc-058d4eda-2800-42ae-9859-f3518db541a9   7Gi        RWO            csi-cinder-sc-delete   5d21h
data-caas-opensearch-data-nodes-1         Bound    pvc-af24413f-2eaf-4743-b234-2fc27c682cbf   7Gi        RWO            csi-cinder-sc-delete   5d20h
data-caas-opensearch-data-nodes-2         Bound    pvc-f270c56a-8ea6-4228-9177-ef4e554dceff   7Gi        RWO            csi-cinder-sc-delete   5d20h
```

Check the pods filesystem:

Pod-0:
```
/dev/vdh        5.9G  5.5M  5.9G   1% /usr/share/opensearch/data
```

Pod-1:
```
/dev/vdg        5.9G  5.1M  5.9G   1% /usr/share/opensearch/data
```

Pod-2:
```
/dev/vdi        4.9G  1.8M  4.9G   1% /usr/share/opensearch/data
```

So we can see that somehow 2 out of 3 pods saw the first resizing to 6Gi, but not the second resizing to 7Gi. 
The 3rd pod is still as if no resizing took place.

I tried to delete the pods, but it doesn't help.

### What is the expected behavior?
The PVCs should be 7Gi.
When checking the filesystem from inside the pod (`df -h`), the filesystem should be 7 gigabytes.

### What is your host/environment?
Operator version 2.5.1 (also tested with 2.4.0).
