### ISSUE TITLE
[BUG] There is no way to configure some security plugin settings

### ISSUE THREAD

**Issue by vchirikov** [opensearch-project/opensearch-k8s-operator#736]
Hi, looks like there is no way to configure some of `plugins.security` config:

Example:

https://github.com/opensearch-project/opensearch-k8s-operator/blob/c3d2a79f932b9a6e02e742318911e93b5d511b11/opensearch-operator/pkg/reconcilers/configuration.go#L66-L67

I have:

```yaml
#...
  general:
    additionalConfig:
      # doesn't work here (?)
      plugins.security.restapi.roles_enabled: '["all_access", "security_rest_api_access", "full_access"]'
      plugins.security.system_indices.enabled: "false"
#...
```

I see the default settings in `opensearch-config` ConfigMap.

```yaml
plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
plugins.security.system_indices.enabled: true
```

Also see my overrides provided via environment variables in pod, but looks like they doesn't work.
There is a way to disable system indices protection?
