### ISSUE TITLE
[BUG] Operator takes ownership of adminCredentialsSecret that wasn't created by it

### ISSUE THREAD

**Issue by L1ghtman2k** [opensearch-project/opensearch-k8s-operator#763]
### What is the bug?
An operator takes ownership of the secret that wasn't created by it. As a result, the operator deletes the secret, when the cluster is deleted, even though the operator wasn't supposed to manage said resource.

### What is the expected behavior?
The secret that was created by a different processor other than operator should remain

**Comment by prudhvigodithi** [comment]
[Triage]

Hey @L1ghtman2k I have tested the creation of admin secret `admin-credentials-secre` (`kubectl create -f <>`) and updated the `adminCredentialsSecret` section of the config file, I was able to get the cluster created by the operator and able to access the cluster with `admin:test`.


```
apiVersion: v1
kind: Secret
metadata:  
  name: admin-credentials-secret
type: Opaque
data:
  # admin
  username: YWRtaW4=
  # test
  password: dGVzdA==
```

```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: pgcluster
  namespace: default
spec:
  security:
    config: 
     adminCredentialsSecret:
        name: admin-credentials-secret
    tls:
       http:
         generate: true 
       transport:
         generate: true
         perNode: true
  general:
    httpPort: 9400
    serviceName: my-first-cluster
    version: 2.12.0
    drainDataNodes: true
  dashboards:
    version: 2.12.0
    enable: true
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: masters
      replicas: 3
      resources:
         requests:
            memory: "1Gi"
            cpu: "550m"
         limits:
            memory: "1Gi"
            cpu: "550m"
      roles:
        - "data"
        - "cluster_manager"
      persistence:
         emptyDir: {}

```

After I delete the cluster by deleting the config file (`kubectl delete -f <>`), the cluster was deleted but not the secret `admin-credentials-secret` that was created separately. 

Adding @bbarani @salyh @jochenkressin @pchmielnik @bbarani
