### ISSUE TITLE
[FEATURE] Add maskedFields to OpensearchRole

### ISSUE THREAD

**Issue by cgroschupp** [opensearch-project/opensearch-k8s-operator#765]
To support [field masking](https://opensearch.org/docs/latest/security/access-control/field-masking/) it is necessary to add `maskedFields` to the `indexPermissions` within the `OpensearchRole` resource.

Example OpensearchRole:
```yaml
apiVersion: opensearch.opster.io/v1
kind: OpensearchRole
metadata:
  name: mask
spec:
  opensearchCluster:
    name: test
  name: mask
  indexPermissions:
    - indexPatterns:
        - "*"
      allowedActions:
        - "read"
      maskedFields:
        - "message"
```
