### ISSUE TITLE
[FEATURE] Support dataStream inside OpensearchIndexTemplate

### ISSUE THREAD

**Issue by cgroschupp** [opensearch-project/opensearch-k8s-operator#766]
To allow [data streams](https://opensearch.org/docs/latest/im-plugin/data-streams/) to be created directly from an index template, it is necessary to support this in the `OpensearchIndexTemplate` resource.

Example OpensearchIndexTemplate:
```yaml
apiVersion: opensearch.opster.io/v1
kind: OpensearchIndexTemplate
metadata:
  name: logs
spec:
  opensearchCluster:
    name: test
  name: logs
  indexPatterns:
    - "logs-*"
  dataStream: {}
```
