### ISSUE TITLE
[BUG] Upgrade from OpenSearch 2.8.0 to 2.11.1 does not complete and cluster remains in a yellow state

### ISSUE THREAD

**Issue by nilushancosta** [opensearch-project/opensearch-k8s-operator#779]
### What is the bug?
I tested upgrading OpenSearch from 2.8.0 to 2.11.1 using the OpenSearch Operator. I deployed the operator and a 3 node OpenSearchCluster using Helm. Once the upgrade started, one of the OpenSearch pods got terminated and a new one came up to replace it (running the new 2.11.1 version). But the other two pods remained and the upgrade didn't continue.

Output of `kubectl get OpenSearchCluster`
```
NAME                 HEALTH   NODES   VERSION   PHASE     AGE
opensearch-cluster   yellow   3       2.8.0     RUNNING   44m
```
<br/>

Part of the output of `kubectl describe OpenSearch`
```yaml
Status:
  Available Nodes:  3
  Components Status:
    Component:  Upgrader
    Conditions:
      cluster is not green and drain nodes is enabled
    Description:  masters
    Status:       Upgrading
    Component:    Upgrader
    Conditions:
      cluster is not green and drain nodes is enabled
    Description:  masters
    Status:       Upgrading
  Health:         yellow
  Initialized:    true
  Phase:          RUNNING
  Version:        2.8.0
Events:
  Type    Reason    Age                From                     Message
  ----    ------    ----               ----                     -------
  Normal  Security  66m                containerset-controller  Starting to securityconfig update job
  Normal  Upgrade   27m (x2 over 27m)  containerset-controller  Starting upgrade of node pool 'masters'
```

<br/>
operator-controller-manager container (in operator pod) keeps printing these logs

```json
{"level":"info","ts":"2024-04-05T08:11:15.094Z","msg":"Reconciling OpenSearchCluster","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchCluster":{"name":"opensearch-cluster","namespace":"test-ns"},"namespace":"test-ns","name":"opensearch-cluster","reconcileID":"921912f4-acff-497a-afc5-4bb73e51383e","cluster":{"name":"opensearch-cluster","namespace":"test-ns"}}
{"level":"info","ts":"2024-04-05T08:11:15.379Z","msg":"Generating certificates","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchCluster":{"name":"opensearch-cluster","namespace":"test-ns"},"namespace":"test-ns","name":"opensearch-cluster","reconcileID":"921912f4-acff-497a-afc5-4bb73e51383e","interface":"transport"}
{"level":"info","ts":"2024-04-05T08:11:15.379Z","msg":"Generating certificates","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchCluster":{"name":"opensearch-cluster","namespace":"test-ns"},"namespace":"test-ns","name":"opensearch-cluster","reconcileID":"921912f4-acff-497a-afc5-4bb73e51383e","interface":"http"}
{"level":"info","ts":"2024-04-05T08:11:15.380Z","msg":"Not passed any SecurityconfigSecret","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchCluster":{"name":"opensearch-cluster","namespace":"test-ns"},"namespace":"test-ns","name":"opensearch-cluster","reconcileID":"921912f4-acff-497a-afc5-4bb73e51383e"}
{"level":"info","ts":"2024-04-05T08:11:15.385Z","msg":"ServiceMonitor crd not found, skipping deletion","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchCluster":{"name":"opensearch-cluster","namespace":"test-ns"},"namespace":"test-ns","name":"opensearch-cluster","reconcileID":"921912f4-acff-497a-afc5-4bb73e51383e"}
{"level":"info","ts":"2024-04-05T08:11:15.684Z","msg":"Cluster is not ready for next pod to restart because cluster is not green and drain nodes is enabled","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchCluster":{"name":"opensearch-cluster","namespace":"test-ns"},"namespace":"test-ns","name":"opensearch-cluster","reconcileID":"921912f4-acff-497a-afc5-4bb73e51383e","reconciler":"upgrade"}
```

I know that the [compatibility chart](https://github.com/opensearch-project/opensearch-k8s-operator?tab=readme-ov-file#compatibility) does not list 2.11.1. Since Newer minor versions not listed there are generally also said to work, I wanted to test this in a test setup. Is this a known issue that will get fixed when 2.11.1 is officially supported?

### How can one reproduce the bug?
1. Using Helm, install the OpenSearch operator and then install an OpenSearch cluster with `2.8.0` as the version in [opensearchCluster.general.version](https://github.com/opensearch-project/opensearch-k8s-operator/blob/4b0fe24eda76aa809141ba2ffaa5f3bf8cc7bd35/charts/opensearch-cluster/values.yaml#L7)
2. Change [opensearchCluster.general.version](https://github.com/opensearch-project/opensearch-k8s-operator/blob/4b0fe24eda76aa809141ba2ffaa5f3bf8cc7bd35/charts/opensearch-cluster/values.yaml#L7) from 2.8.0 to 2.11.1 and execute a `helm upgrade`
3. One OpenSearch pod will get terminated and a new one will be created and come into a running state (with version 2.11.1)
4. The upgrade does not proceed further after this

### What is the expected behavior?
I also tested an upgrade from 2.7.0 to 2.8.0 on the same setup. Here the upgrade completed and the `Health` of the `OpenSearchCluster` resource became `green`. During the upgrade, pods got terminated one at a time and new pods with version 2.8.0 came up. Thereafter a rolling restart took place. So I expected the same behaviour

### What is your host/environment?
I tried this on Rancher Desktop on MacOS. Kubernetes version: v1.25.11

Helm chart versions
opensearch-operator/opensearch-operator: 2.5.1 
opensearch-operator/opensearch-cluster: 2.5.1

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
`opensearch-operator/opensearch-operator` was deployed with default values.

values file used with `opensearch-operator/opensearch-cluster` helm chart is as follows
```yaml
opensearchCluster:
  enabled: true
#  bootstrap:
#    Configure settings for the bootstrap pod
  general:
    httpPort: "9200"
    version: 2.11.1
    serviceName: "opensearch"
    drainDataNodes: true
    setVMMaxMapCount: true
#    securityContext:
#       Specify container security context for OpenSearch pods
#    podSecurityContext:
#       Specify pod security context for OpenSearch pods
  dashboards:
    enable: false
    replicas: 1
    version: 2.3.0
#        securityContext:
#           Specify container security context for OSD pods
#        podSecurityContext:
#           Specify pod security context for OSD pods
    resources:
      requests:
        memory: "1Gi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "400m"
  nodePools:
    - component: masters
      diskSize: "2Gi"
      replicas: 3
      roles:
        - "master"
        - "data"
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "500m"
  security:
    tls:
      transport:
        generate: true
      http:
        generate: true
```
