### ISSUE TITLE
[BUG] ISM CRD allocation action is broken

### ISSUE THREAD

**Issue by Jerrimikkihvatai** [opensearch-project/opensearch-k8s-operator#829]
### What is the bug?
I can't create an ISM policy with only one allocation parameter, though I can do it via api or Opensearch dashboards.
I get the following error:
```
one or more objects failed to apply, reason: OpenSearchISMPolicy.opensearch.opster.io "delete-more-30d" is invalid: [spec.states[1].actions[0].allocation.exclude: Required value, spec.states[1].actions[0].allocation.include: Required value, spec.states[1].actions[0].allocation.waitFor: Required value]
```

Seems that the problem is in [required field in ISM CRD ](https://github.com/opensearch-project/opensearch-k8s-operator/blob/main/charts/opensearch-operator/files/opensearch.opster.io_opensearchismpolicies.yaml#L200)

### How can one reproduce the bug?
Try to create ISM CRD like that
```
---
apiVersion: opensearch.opster.io/v1
kind: OpenSearchISMPolicy
metadata:
   name: delete-more-30d
   namespace: devops-opensearch-infra
spec:
   opensearchCluster:
      name: opensearch-prod
   description: Delete indices older than 30 days
   policyId: delete_more_30d
   defaultState: open
   ismTemplate:
      priority: 1
      indexPatterns:
         - "testindex-*"
   states:
      - name: open
        actions:
           - open: {}
        transitions:
           - stateName: cold
             conditions:
                minIndexAge: "15d"
      - name: cold
        actions:
           - allocation:
                require: "temp: cold"
        transitions:
           - stateName: delete
             conditions:
                minIndexAge: "30d"
      - name: delete
        actions:
           - delete: {}
---
```

### What is the expected behavior?
I expect to create an ISM policy with only one parameter

### What is your host/environment?
OS 2.14, operator 2.6.0

### Do you have any additional context?
[I noticed confusing information on os docs about allocation action ](https://opensearch.org/docs/latest/im-plugin/ism/policies/#allocation)
It says that all parameters are required, though you can create an ISM policy with only one of them (include, exclude, required)
I also noticed wrong description of crd fields [there](https://github.com/opensearch-project/opensearch-k8s-operator/blob/main/charts/opensearch-operator/files/opensearch.opster.io_opensearchismpolicies.yaml#L184)

**Comment by prudhvigodithi** [comment]
[Triage]
Hey @cthtrifork can you please check this, I assume your contribution in this PR https://github.com/opensearch-project/opensearch-k8s-operator/pull/788 should fix the error.
Thanks
@getsaurabh02

**Comment by prudhvigodithi** [comment]
Similiar issue related to this topic https://github.com/opensearch-project/opensearch-k8s-operator/issues/812#issuecomment-2181387505.

**Comment by rkthtrifork** [comment]
From a quick look at the code, it looks like the ism policy object does not require all 4 to be set so I believe it's just in the CRD which should be a quick fix. I might do it on monday

**Comment by dgsardina** [comment]
I am hitting this same issue on 2.7.0.

**Comment by rameshar16** [comment]
I am also facing the similar issue with 2.7.0.

**Comment by rameshar16** [comment]
Added the below config and did nnot notice any issue during the deployment.

 - name: "warm"
        actions:
          - allocation:
              require: "temp: warm"
              include: ""
              exclude: ""
              waitFor: "1m"
        transitions:
          - stateName: "cold"
            conditions:
              minIndexAge: "15d"
      - name: "cold"
        actions:
          - allocation:
              require: "temp: warm"
              include: ""
              exclude: ""
              waitFor: "1m"
        transitions:
          - stateName: "delete"
            conditions:
              minIndexAge: "30d"

**Comment by prudhvigodithi** [comment]
Thanks @rameshar16 can you please create a PR to update the [docs](https://github.com/opensearch-project/opensearch-k8s-operator/blob/main/docs/userguide/main.md ) and some [examples](https://github.com/opensearch-project/opensearch-k8s-operator/tree/main/opensearch-operator/examples/2.x )?

**Comment by rameshar16** [comment]
Hi @prudhvigodithi ,

I did not see any see after I added the below data for allocation along with the require field.

include: ""
exclude: ""
waitFor: "1m"

Below is the completed template:

`ismPolicies:
  - name: hot-warm-cold-delete-policy
    defaultState: "hot"
    description: hot-warm-cold-delete-policy
    states:
      - name: "hot"
        actions: []
        transitions:
          - stateName: "warm"
            conditions:
              minIndexAge: "7d"
      - name: "warm"
        actions:
          - allocation:
              require: "temp: warm"
              include: ""
              exclude: ""
              waitFor: "1m"
        transitions:
          - stateName: "cold"
            conditions:
              minIndexAge: "15d"
      - name: "cold"
        actions:
          - allocation:
              require: "temp: warm"
              include: ""
              exclude: ""
              waitFor: "1m"
        transitions:
          - stateName: "delete"
            conditions:
              minIndexAge: "30d"
      - name: "delete"
        actions:
          - delete: {}
        transitions: []
    ismTemplate:
      priority: 0
      indexPatterns:
        - "log-*"`

**Comment by rameshar16** [comment]
I did not see any error during the deployment with above configurations, but the ISM Polices did not create with the below configs.

          # - allocation:
          #     require: "temp: warm"
          #     include: ""
          #     exclude: ""
          #     waitFor: "1m"


Have removed and redeployed.

**Comment by rameshar16** [comment]
I am getting the below error with below config.

- name: "hot"
        actions:
          - allocation:
              require:
                temp: "hot"
              include: {}
              exclude: {}
              waitFor: "1m"
        transitions:
          - stateName: "warm"
            conditions:
              minIndexAge: "7d"


W1224 00:31:34.676507   43198 warnings.go:70] unknown field "spec.states[0].actions[0].allocation.require.temp"
Error: UPGRADE FAILED: cannot patch "hot-warm-cold-delete-policy" with kind OpenSearchISMPolicy: OpenSearchISMPolicy.opensearch.opster.io "hot-warm-cold-delete-policy" is invalid: [spec.states[0].actions[0].allocation.require: Invalid value: "object": spec.states[0].actions[0].allocation.require in body must be of type string: "object", spec.states[0].actions[0].allocation.exclude: Invalid value: "object": spec.states[0].actions[0].allocation.exclude in body must be of type string: "object", spec.states[0].actions[0].allocation.include: Invalid value: "object": spec.states[0].actions[0].allocation.include in body must be of type string: "object"]

**Comment by lucasfcnunes** [comment]
@saegel

```yaml
        - name: hot
          actions:
            - allocation:
                require: "type: hot" # <<< should be "temp: hot" not "type: hot"
                include: ""
                exclude: ""
                waitFor: "false"

```
