### ISSUE TITLE
[BUG] ISM policies and index templates are constantly updated

### ISSUE THREAD

**Issue by lpeter91** [opensearch-project/opensearch-k8s-operator#833]
Operator version: 2.6.0

The following very simple ISM template and index template get constantly updated by the operator. (The operator logs "policy exists and requires update" and "Index template requires update" respectively.)

ISM template:

```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchISMPolicy
metadata:
  name: soc-policy
spec:
  opensearchCluster:
    name: opensearch
  policyId: soc-policy
  description: "SOC ISM policy"
  defaultState: hot
  states:
    - name: hot
      actions:
        - rollover:
            minIndexAge: "14d"
            minPrimaryShardSize: 10gb
          retry:
            count: 3
            backoff: exponential
            delay: 1m
      transitions:
        - stateName: delete
          conditions:
            minRolloverAge: "365d"
    - name: delete
      actions:
        - delete: { }
          retry:
            count: 3
            backoff: exponential
            delay: 1m
  ismTemplate:
    indexPatterns:
      - "logs-*"
      - "probe-*"
    priority: 1000
```

Index template:

```
apiVersion: opensearch.opster.io/v1
kind: OpensearchIndexTemplate
metadata:
  name: logs-generic
spec:
  composedOf:
    - soc-ecs-mappings
    - soc-settings
    - soc-mappings
  dataStream: {}
  indexPatterns:
    - logs-*
  name: logs-generic
  opensearchCluster:
    name: opensearch
  priority: 300
```

Now these are just examples, in reality most (maybe even all) of my ISM policies and index templates are constantly updated. In fact, my component templates also get updated all the time, but that might be fixed by the unreleased #809. (Btw please do a release, without the fix for #801 the operator isn't really usable in a conventional way.)

For the index templates the issue might be with the data stream, to which the default timestamp field is added. But in general it seems to me that this "diffing" approach is very fragile and destined to break over time. Maybe an other way to handle this should be considered, some very vague ideas:
* Storing (writing back to the K8s resource?) the API representation of the resource
* Only keeping this diffing as a performance optimization, reducing the log level to debug and increasing the time between reconcile iterations (could be configurable)
