### ISSUE TITLE
[BUG] Security config handling means either API/Dashboard-created Users are deleted or you're stuck with default admin credentials

### ISSUE THREAD

**Issue by dmantas** [opensearch-project/opensearch-k8s-operator#839]
### What is the bug?
The way security config is implemented leads to an undesired dilemma in case you want to manage users on the OS platform via OS Dashboards or the API.

The fact that both internal users and security config are in the same secret means that the management of both is interconnected.

The implementation of [this](https://github.com/opensearch-project/opensearch-k8s-operator/issues/493) PR improved things, but did not solve the issue.

### How can one reproduce the bug?
You basically have 2 options:
1. In security config `internal_users.yml` you define `admin` user with a custom password plus your security config under `config.yml`. You then create other users in OS using e.g. OS Dashboards or the OS API. If you need to make a change in `config.yml`, the Operator will detect this and run the security admin job, which will also overwrite your users, because in security config the `internal_users.yml` file is present.
2. In security config you only define `config.yml`. This means that `admin` user will have the default (`admin`) password. You then create other users using Dashboards or the API. If you need to make a change in `config.yml` then, because `internal_users.yml` is not defined in security config, the users you have created will remain in place. But this means that you're stuck with default admin credentials forever which is a security issue.

### What is the expected behavior?
I see there are two options:
1. Separate `config.yml` with users/roles/etc configuration. Changes in `config.yml` should only trigger this part of the config to be changed and not touch users/roles/etc.
2. Create more complex default password for `admin` user like requested [here](https://github.com/opensearch-project/opensearch-k8s-operator/issues/380). You're again stuck with it (i.e. if you try to change this you will overwrite your users), but at least it will not be `admin`/`admin`.

Thank you in advance.

**Comment by prudhvigodithi** [comment]
[Triage]
Adding @saketmht and @swoehrl-mw to please help @dmantas here.
Thank you 
@salyh @pchmielnik @jochenkressin

**Comment by swoehrl-mw** [comment]
Hi @dmantas. This is currently a limitation of the operator that are discussed in several issues: #571, #254, #221. 
Right now you can only use either securityconfig or CRDs for user management.

**Comment by vinylen** [comment]
> Hi [@dmantas](https://github.com/dmantas). This is currently a limitation of the operator that are discussed in several issues: [#571](https://github.com/opensearch-project/opensearch-k8s-operator/issues/571), [#254](https://github.com/opensearch-project/opensearch-k8s-operator/issues/254), [#221](https://github.com/opensearch-project/opensearch-k8s-operator/issues/221). Right now you can only use either securityconfig or CRDs for user management.

This is not quite true, because that assumes that you never want to change the admin password if you are using CRDs. As far as i can tell from testing and reading the docs, using the CRDs to manage users in opensearch only works if you do not want to change the default admin password.

So really CRDs in real world production use is basically a non-option because of the inability to change the admin password.

EDIT: I found a potential workaround. Basically, configure the admin secret and reference it for the cluster and dashboard spec, like this:

```
---
apiVersion: v1
kind: Secret
metadata:
  name: lab-admin-credentials-secret
type: Opaque
data:
  # admin
  username: YWRtaW4=
  # admin123
  password: YWRtaW4xMjM=
---
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: lab
  namespace: opensearch
spec:
  dashboards:
    enable: true
    version: 3.2.0
    replicas: 1
    tls:
      enable: false
      generate: false
    opensearchCredentialsSecret:
      name: lab-admin-credentials-secret
  general:
    httpPort: 9200
    serviceName: lab
    setVMMaxMapCount: true
    version: 3.2.0
  security:
    tls:
      http:
        generate: true
      transport:
        generate: true
        perNode: true
    config:
      adminCredentialsSecret:
        name: lab-admin-credentials-secret
```

After the cluster has been deployed and the securityconfig pod has run it's course, the opensearch-security plugin will be initialized. The cluster is still using the admin/admin credentials, but the operator and it's components thinks that the right credentials are according to the `lab-admin-credentials-secret` we created so the pods will never be in a ready state.

This is when you have to do a manual fix, upload the internal_users.yml to the cluster via securityadmin.sh. This is all done from within one of the master pods but that doesn't really matter:

### Step 1. Extract the admin certs
```
SECRET_NAME=lab-admin-cert
NAMESPACE=opensearch

 kubectl get secret ${SECRET_NAME} -n ${NAMESPACE} -o jsonpath='{.data.ca\.crt}' | base64 --decode > admin-ca.pem
 kubectl get secret ${SECRET_NAME} -n ${NAMESPACE} -o jsonpath='{.data.tls\.crt}' | base64 --decode > admin-cert.pem
 kubectl get secret ${SECRET_NAME} -n ${NAMESPACE} -o jsonpath='{.data.tls\.key}' | base64 --decode > admin-key.pem
 
```
### Step 2. Copy the certs and key to the pod
```
kubectl cp admin-ca.pem lab-masters-0:/usr/share/opensearch/
kubectl cp admin-cert.pem lab-masters-0:/usr/share/opensearch/
kubectl cp admin-key.pem lab-masters-0:/usr/share/opensearch/
```
### Step 3. Create the internal_users.yml with the hashed admin password and copy it to the pod as well

```
_meta:
  type: "internalusers"
  config_version: 2
admin:
  hash: "$2a$12$HjnuQy7cKa5KciLAtEw.A.Gpq0Cxr6lYxeQ/SZf2TbsUXcVPW58jC"
  reserved: true
  backend_roles:
    - "admin"
  description: "Demo admin user"
```
Copy internal_users.yml to the pod
```
kubectl cp internal_users.yml lab-masters-0:/usr/share/opensearch/
```

### Step 4. Run securityadmin.sh from the pod to change the password of the admin user

```
kubectl exec -it lab-masters-0 -- bash
```
And now from within the pod run this:
```
/usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh   -cacert /usr/share/opensearch/admin-ca.pem   -cert /usr/share/opensearch/admin-cert.pem   -key /usr/share/opensearch/admin-key.pem -icl -nhnv -t internalusers -f internal_users.yml
```

This will update the admin password according to what we specified in the `lab-admin-credentials-secret`, and you can now manage users via the CRDs as well.
