### ISSUE TITLE
[BUG] Annotations conflict when using a single Secret for multiple users

### ISSUE THREAD

**Issue by evheniyt** [opensearch-project/opensearch-k8s-operator#884]
In our configuration, we have a single Secret `users-credentials` which contains passwords for multiple Opensearch users.
Users configuration looks like this:
```yaml
  users:
    - name: backup-and-restore
      secretName: users-credentials
      secretKey: backup-and-restore
    - name: collections
      secretName: users-credentials
      secretKey: collections
    - name: es-consumer
      secretName: users-credentials
      secretKey: es-consumer
```
So each user takes it's password from the `users-credentials` Secret, where the password is a dedicated Secret key.
But after Operator created these users, we could see constant changes in Secret annotations. During reconciling loop [Operator updates Secret annotation](https://github.com/opensearch-project/opensearch-k8s-operator/blob/main/opensearch-operator/pkg/reconcilers/users.go#L247) for each user.

I think it's a pretty common scenario when we are taking Secret from some external secret manager and want to share it by multiple users. Do we really need to set these annotations for the Secret?
