### ISSUE TITLE
[BUG] didn't apply CDRs with change admin password

### ISSUE THREAD

**Issue by w1ndblow** [opensearch-project/opensearch-k8s-operator#900]
When i changed  default admin password with config 
```
  security:
    config:
      adminCredentialsSecret: 
        name: <secret with password>
```

I take side effect with CRDs:
```
Events:
---
 Warning  OpensearchRefMismatch  29s (x20 over 39m)    userrolebinding-controller  cannot change the cluster a userrolebinding refers to

```

**Comment by bshien** [comment]
[Triage] Is the cluster up with the admin password changed?

**Comment by w1ndblow** [comment]
that's right

**Comment by bshien** [comment]
@prudhvigodithi @swoehrl-mw Can you take a look at this issue? Thanks

**Comment by w1ndblow** [comment]
yes, i recreated cluster. i didn't remember but it seems me like i recreated crd resource too
i  can't  get config  because i already resolved problem with `additionalVolumes:` where applied  needed security config like this 
``` yaml
spec:
  general:
...
     additionalVolumes:
      - name: internalusers
        path: /usr/share/opensearch/config/opensearch-security/internal_users.yml
        subPath: internal_users.yml
...
  security:
    config:
      adminCredentialsSecret: 
        name: os-cluster-admin-password-changed
```
and new apply of crd works!
but i don't understand why it works this way, my recreated cluster had same name like older and cdrs  have not  fields like `id`, why controller can't use same config of cdrs
may be worth doing do this warning on logs?
thanks for answer anyway
