### ISSUE TITLE
Log4j2 logs in json

### ISSUE THREAD

**Issue by gabriel-suela** [opensearch-project/opensearch-k8s-operator#901]
How can i change the settings for log4j2.properties? Currently im trying to change in the `securityconfig-secret` :

```yaml
  - apiVersion: v1
    kind: Secret
    metadata:
      name: securityconfig-secret
    stringData:
      log4j2.properties: |-
        appender.console.type = Console
        appender.console.name = console
        appender.console.layout.type = OpenSearchJsonLayout
        appender.console.layout.type_name = json_logger

        rootLogger.level = info
        rootLogger.appenderRef.console.ref = console
```
        
but when i check the log4j2.properties in the container the settings do not change.

```
[opensearch@opensearch-cluster-masters-0 config]$ cat log4j2.properties
# Copyright OpenSearch Contributors
# SPDX-License-Identifier: Apache-2.0
#
# The OpenSearch Contributors require contributions made to
# this file be licensed under the Apache-2.0 license or a
# compatible open source license.

status = error

appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}] [%node_name]%marker %m%n

rootLogger.level = info
rootLogger.appenderRef.console.ref = console
```

**Comment by swoehrl-mw** [comment]
Hi @gabriel-suela. The securityconfig-secret is, as the name implies, only for the securityconfig, so adding log4j properties there will have no effect.
There is currently no dedicated way to provide a custom `log4j2.properties` file, but you can mount your own file using the [additional volumes](https://github.com/opensearch-project/opensearch-k8s-operator/blob/main/docs/userguide/main.md#additional-volumes) feature.

**Comment by gabriel-suela** [comment]
@swoehrl-mw ty for the information. 
for anyone in the future that will come here:

```yaml
general:
    additionalVolumes:
      - name: log4j2-properties
        path: /usr/share/opensearch/config/log4j2.properties
        subPath: log4j2.properties
        configMap:
          name: log4j2-properties
        restartPods: true
```
configMap:
```yaml
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: log4j2-properties
    data:
      log4j2.properties: |-
        appender.console.type = Console
        appender.console.name = console
        appender.console.layout.type = OpenSearchJsonLayout
        appender.console.layout.type_name = json_logger
        rootLogger.level = info
        rootLogger.appenderRef.console.ref = console
```
