### ISSUE TITLE
[PROPOSAL] Apply GPU acceleration to ML Node in k8s operator 

### ISSUE THREAD

**Issue by YeonghyeonKO** [opensearch-project/opensearch-k8s-operator#906]
### What are you proposing?
As @stevapple has already suggested [the way](https://github.com/opensearch-project/opensearch-k8s-operator/issues/832) how to override CUDA image in nodePools[] in opensearch k8s oprator, this issue is an extended discussion with that concept. 

1) Provision GPU-dedicated Worker Node(s) in the existing K8s cluster.
2) Prepare CUDA-based image for OpenSearch
3) Deploy OpenSearch ml-node(s) using nodeSelector in opensearch k8s operator.
    -  CR has already offered us `nodeSelector` property as below:
```yaml
  nodePools:
    - component: ml
      replicas: 3
      diskSize: "10Gi"
      nodeSelector: # <- assign ml node(ie. Pod) to GPU Worker Node 
      roles:
        - "ml"
      resources:
        requests:
        limits:
```
4) Test whether ML Node does use GPU resource or not.

<br>

But this is all for now because we can't set a GPU-enabled image for opensearch, except `opensearchCluster.general.image` in yaml.
Is there any further progress in this idea?
For implementing [GPU acceleration - OpenSearch Documentation](https://opensearch.org/docs/latest/ml-commons-plugin/gpu-acceleration/), we need guidelines and an exact standard for it.
