### ISSUE TITLE
[BUG] Opensearch operator does not properly append the opensearch.yml file when general.additionalConfig is specified

### ISSUE THREAD

**Issue by digitalray** [opensearch-project/opensearch-k8s-operator#920]
### What is the bug?
When you specify key pairs to general.additionalConfig, the operator adds those to the env instead of the opensearch.yml file. This is not the case when specifying dashboard.additionalConfig. In the Dashboard case, the additional values are appended to the dashboard config file.

### How can one reproduce the bug?
1. Specify general.additionalConfig and dashboard.additionalConfig in OpensearchCluster manifest and deploy the cluster. 

```yaml
general:
    additionalConfig:
      s3.client.default.endpoint: "s3.test.svc.cluster.local:9020"
      s3.client.default.protocol: "https"
      s3.client.default.max_retries: "3"
      s3.client.default.path_style_access: "false"
      s3.client.default.read_timeout: "50s"
      s3.client.default.use_throttle_retries: "true"
```
```yaml
dashboard:
    additionalConfig:
      logging.verbose: "true"
      opensearch.requestHeadersWhitelist: |
        ["authorization", "securitytenant"]
      opensearch_security.auth.type: |
        ["basicauth", "openid"]
      opensearch_security.auth.multiple_auth_enabled: "true"
      opensearch_security.multitenancy.enabled: "true"
      opensearch_security.multitenancy.tenants.preferred: |
        [ "Private", "Global" ]
      opensearch_security.readonly_mode.roles: |
        ["kibana_read_only"]
```

2. Check config map for opensearch cluster vs dashboard:
```shell
kubectl get cm opensearch-cluster-config -n opensearch -o yaml
```
```yaml
apiVersion: v1
data:
  opensearch.yml: |
    plugins.security.audit.type: internal_opensearch
    plugins.security.authcz.admin_dn: ["CN=admin,OU=opensearch-cluster"]
    plugins.security.check_snapshot_restore_write_privileges: true
    plugins.security.enable_snapshot_restore_privilege: true
    plugins.security.nodes_dn: ["CN=opensearch-cluster,OU=opensearch-cluster"]
    plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
    plugins.security.ssl.http.enabled: true
    plugins.security.ssl.http.pemcert_filepath: tls-http/tls.crt
    plugins.security.ssl.http.pemkey_filepath: tls-http/tls.key
    plugins.security.ssl.http.pemtrustedcas_filepath: tls-http/ca.crt
    plugins.security.ssl.transport.enforce_hostname_verification: false
    plugins.security.ssl.transport.pemcert_filepath: tls-transport/tls.crt
    plugins.security.ssl.transport.pemkey_filepath: tls-transport/tls.key
    plugins.security.ssl.transport.pemtrustedcas_filepath: tls-transport/ca.crt
    plugins.security.system_indices.enabled: true
    plugins.security.system_indices.indices: [".opendistro-alerting-config",".opendistro-alerting-alert*",".opendistro-anomaly-results*",".opendistro-anomaly-detector*",".opendistro-anomaly-checkpoints",".opendistro-anomaly-detection-state",".opendistro-reports-*",".opendistro-notifications-*",".opendistro-notebooks",".opensearch-observability",".opendistro-asynchronous-search-response*",".replication-metadata-store"]
kind: ConfigMap
```

```shell
kubectl get cm opensearch-cluster-dashboards-config -n opensearch -o yaml
```

```yaml
apiVersion: v1
data:
  opensearch_dashboards.yml: |
    logging.verbose: true
    opensearch.requestHeadersWhitelist: ["authorization", "securitytenant"]

    opensearch.ssl.verificationMode: none
    opensearch_security.auth.multiple_auth_enabled: true
    opensearch_security.auth.type: ["basicauth", "openid"]
    opensearch_security.multitenancy.enabled: true
    opensearch_security.multitenancy.tenants.enable_global: true
    opensearch_security.multitenancy.tenants.enable_private: true
    opensearch_security.multitenancy.tenants.preferred: [ "Private", "Global" ]
    opensearch_security.readonly_mode.roles: ["kibana_read_only"]

    server.name: opensearch-cluster-dashboards
kind: ConfigMap
```

2. Check env vars of opensearch cluster vs dashboard:
```shell
kubectl describe sts opensearch-cluster-masters | grep -v "<none>" | grep Env -A 14
    Environment:
      cluster.initial_master_nodes:            opensearch-cluster-bootstrap-0
      discovery.seed_hosts:                    opensearch-cluster-discovery
      cluster.name:                            opensearch-cluster
      network.bind_host:                       0.0.0.0
      network.publish_host:                     (v1:metadata.name)
      OPENSEARCH_JAVA_OPTS:                    -Xmx1024M -Xms1024M -Dopensearch.transport.cname_in_publish_address=true
      node.roles:                              cluster_manager,data
      http.port:                               9200
      s3.client.default.endpoint:              s3.test.svc.cluster.local:9020
      s3.client.default.max_retries:           3
      s3.client.default.path_style_access:     false
      s3.client.default.protocol:              http
      s3.client.default.read_timeout:          50s
      s3.client.default.use_throttle_retries:  true
 ```
 
 ```shell
 ❯ kubectl describe deployment opensearch-cluster-dashboards | grep -v "<none>" | grep Env -A 5
    Environment:
      OPENSEARCH_HOSTS:     https://opensearch-cluster.opensearch.svc.cluster.local:9200
      SERVER_HOST:          0.0.0.0
      OPENSEARCH_USERNAME:  <set to the key 'username' in secret 'admin-credentials-secret'>  Optional: false
      OPENSEARCH_PASSWORD:  <set to the key 'password' in secret 'admin-credentials-secret'>  Optional: false
  ```
  

### What is the expected behavior?
Expected behavior is that when you specify additionalConfig, those key/values need to get appended to the config-map as it is the case with the dashboard. Then after the opensearch.yml file in the pod will get refreshed with those.

### What is your host/environment?
Kubernetes Version: 1.29.9
Kubernetes Node OS: Alma Linux 8

### Do you have any screenshots?
n/a

### Do you have any additional context?
I am trying to add S3 related configuration to the opensearch.yml file via general.additionalConfig section of OpenSearchCluster manifest.

**Comment by rameshar16** [comment]
Hi Team,

I am using the OpenSearch Operator 2.7.0. I am also facing the similar issue.

Thanks,

**Comment by digitalray** [comment]
> Hi Team,
> 
> I am using the OpenSearch Operator 2.7.0. I am also facing the similar issue.
> 
> Thanks,

This is what I use as well. The problem is that env vars do not seem to have an effect on opensearch config changes. Unless maybe you need to set them with a certain prefix. But one thing is for sure, that the dashboard config changes are taking effect properly and the yaml file gets updated OK. Logically, the opensearch.yml would also need to get updated the same way.

**Comment by OlafRadicke** [comment]
I have a similar observation. I am trying to enable mTLS client authentication.

I am using Operator Chart 2.7.0 and the container images in version 2.16.0

In the CRD of the operator I create
`plugins.security.authcz.admin_dn: '[“”CN=client01.opensearch.datenhaus.dev"]'`

Logs from pod securityconfig-update I see errors for:

 `“CN=admin,OU=opensearch-cluster-02”`

The content in the generated ConfigMap is:
`“CN=admin,OU=opensearch-cluster-02”`

In the generated configuration file of the pod (master) I find:
`“CN=admin,OU=opensearch-cluster-02”`

in the (auto-generated) certificate is again to be found:
`OU=opensearch-cluster-02,CN=opensearch-cluster-02`

I'm a bit surprised that the “Best practices for OpenSearch security” explicitly recommends client certificate authentication (https://opensearch.org/docs/latest/security/configuration/best-practices/) and then it doesn't work. Apart from that, the documentation is very confusing on the subject.

**Comment by digitalray** [comment]
I think I now see where I went wrong. It seems like the `general.additionalConfig` section is meant for opensearch env vars; however, the `bootstrap.additionalConfig` referenced in: https://github.com/opensearch-project/opensearch-k8s-operator/blob/main/charts/opensearch-cluster/values.yaml#L117-L119 is meant for opensearch.yml changes. I will try the bootstrap value and will report back if that works.

**Comment by digitalray** [comment]
Just added like so
```yaml
bootstrap:
    additionalConfig:
      s3.client.default.endpoint: "s3.test.svc.cluster.local:9020"
      s3.client.default.protocol: "https"
      s3.client.default.max_retries: "3"
      s3.client.default.path_style_access: "false"
      s3.client.default.read_timeout: "50s"
      s3.client.default.use_throttle_retries: "true"
 ```
 Here is my helm diff
 
 ```yaml
   metadata:
    name: opensearch-cluster
    namespace: opensearch
  spec:
+   bootstrap:
+     additionalConfig:
+
+       s3.client.default.endpoint: s3.test.svc.cluster.local:9020
+       s3.client.default.max_retries: "3"
+       s3.client.default.path_style_access: "false"
+       s3.client.default.protocol: http
+       s3.client.default.read_timeout: 50s
+       s3.client.default.use_throttle_retries: "true"
    initHelper:
 ```
All 3 masters do restart after the apply. However, when I exec to the pod and cat the config, I do not see the additional configs there.

```shell
[opensearch@opensearch-cluster-masters-0 ~]$ cat config/opensearch.yml
plugins.security.audit.type: internal_opensearch
plugins.security.authcz.admin_dn: ["CN=admin,OU=opensearch-cluster"]
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.nodes_dn: ["CN=opensearch-cluster,OU=opensearch-cluster"]
plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.pemcert_filepath: tls-http/tls.crt
plugins.security.ssl.http.pemkey_filepath: tls-http/tls.key
plugins.security.ssl.http.pemtrustedcas_filepath: tls-http/ca.crt
plugins.security.ssl.transport.enforce_hostname_verification: false
plugins.security.ssl.transport.pemcert_filepath: tls-transport/tls.crt
plugins.security.ssl.transport.pemkey_filepath: tls-transport/tls.key
plugins.security.ssl.transport.pemtrustedcas_filepath: tls-transport/ca.crt
plugins.security.system_indices.enabled: true
plugins.security.system_indices.indices: [".opendistro-alerting-config",".opendistro-alerting-alert*",".opendistro-anomaly-results*",".opendistro-anomaly-detector*",".opendistro-anomaly-checkpoints",".opendistro-anomaly-detection-state",".opendistro-reports-*",".opendistro-notifications-*",".opendistro-notebooks",".opensearch-observability",".opendistro-asynchronous-search-response*",".replication-metadata-store"]
```

**Comment by digitalray** [comment]
In the operator code, there seems to be a function that will add the additional config to the opensearch config here: 
https://github.com/opensearch-project/opensearch-k8s-operator/blob/2e78967d3d5868d719442574f5d26ee8fae4a17a/opensearch-operator/pkg/reconcilers/reconcilers.go#L86-L93

But it is not being used for the general.additionalConfig or bootstrap.additionalconfig. Both of those are being used only to set environment variables: 

First here:
https://github.com/opensearch-project/opensearch-k8s-operator/blob/2e78967d3d5868d719442574f5d26ee8fae4a17a/opensearch-operator/pkg/reconcilers/cluster.go#L143-L153

Then here:
https://github.com/opensearch-project/opensearch-k8s-operator/blob/main/opensearch-operator/pkg/builders/cluster.go#L549-L556

**Comment by OlafRadicke** [comment]
@digitalray I am ready to test a patch.

**Comment by swoehrl-mw** [comment]
Hi @digitalray
The `bootstrap.additionalConfig` is only used for the bootstrap pod during inital cluster provisioning, so changing that will have no impact on the config of the nodepools.
`general.additionalConfig` and `nodePools.x.additionalConfig` are the right places to configure settings.
Both are not meant as env vars. Instead the operator uses a mechanism from the opensearch docker image that uses the env vars to generate its opensearch.yaml. The configmap is currently only used for some base and security plugin configuration. Everything else happens via the env var mechanism.

It is a known issue that using the env var mechanism leads to problems (see also #883) and that the whole mechanism should be reworked to directly generate the `opensearch.yaml` in the operator logic.

**Comment by swoehrl-mw** [comment]
@OlafRadicke Regarding your issue: The operator does not allow setting `plugins.security.authcz.admin_dn` and similar directly as these are set internally based on the tls configuration.

**Comment by OlafRadicke** [comment]
@swoehrl-mw does this mean that it is not possible to implement the 'Best practices for OpenSearch security' ( https://opensearch.org/docs/latest/security/configuration/best-practices/ ) and follow the instructions at https://opensearch.org/docs/latest/security/authentication-backends/client-auth/? Because apparently I need the entry `plugins.security.ssl.http.clientauth_mode: OPTIONAL`  or better `REQUIRE`.

**Comment by OlafRadicke** [comment]
@swoehrl-mw 
So this mean too, that it is not possible to enable audit logs? Like this (https://opensearch.org/docs/latest/security/audit-logs/index/):
```yaml
   additionalConfig:
      plugins.security.audit.type: internal_opensearch
```
Plus audit.yml:
```yaml
plugins.security.audit.config.disabled_rest_categories: NONE
plugins.security.audit.config.disabled_transport_categories: NONE
plugins.security.audit.config.log_request_body: false
plugins.security.audit.config.ignore_users: NONE
plugins.security.audit.config.exclude_sensitive_headers: true
```

**Comment by swoehrl-mw** [comment]
> So this mean too, that it is not possible to enable audit logs? Like this (https://opensearch.org/docs/latest/security/audit-logs/index/)

@OlafRadicke 

Haven't tried it but audit logs should be possible, the operator should not interfere there and the `audit.yml` is handled by the securityconfig logic. if something there does not work, please feel free to raise a separate issue.

**Comment by digitalray** [comment]
> #883

Thanks for clarifying how the additional configs would be populated.

When I opened this issue, I was actually using general.additionalConfig. However, it did not populate the opensearch.yml file with my entries. I did confirm that the env vars got created on the pod though with the key/values that I had entered in additionalConfig. Let me try it again and see if I can tail the init container logs maybe can catch something.

**Comment by digitalray** [comment]
> Hi [@digitalray](https://github.com/digitalray) The `bootstrap.additionalConfig` is only used for the bootstrap pod during inital cluster provisioning, so changing that will have no impact on the config of the nodepools. `general.additionalConfig` and `nodePools.x.additionalConfig` are the right places to configure settings. Both are not meant as env vars. Instead the operator uses a mechanism from the opensearch docker image that uses the env vars to generate its opensearch.yaml. The configmap is currently only used for some base and security plugin configuration. Everything else happens via the env var mechanism.
> 
> It is a known issue that using the env var mechanism leads to problems (see also [#883](https://github.com/opensearch-project/opensearch-k8s-operator/issues/883)) and that the whole mechanism should be reworked to directly generate the `opensearch.yaml` in the operator logic.

Thanks for clarifying how the additional configs would be populated.

When I opened this issue, I was actually using general.additionalConfig. However, it did not populate the opensearch.yml file with my entries. I did confirm that the env vars got created on the pod though with the key/values that I had entered in additionalConfig. Let me try it again and see if I can tail the init container logs maybe can catch something.

**Comment by digitalray** [comment]
@swoehrl-mw, I just re-tried with general.additionalConfig with no luck. There are no logs that track the config changes.

It seems like for the dashboard, directly generating the configs currently exists doesn't it? Could we not use the same method for the opensearch config as well?

**Comment by swoehrl-mw** [comment]
@digitalray Providing the entire generated config via configmap will be the way to go, yes. It just requires some rework and additional logic in the operator.

**Comment by OlafRadicke** [comment]
Hi @swoehrl-mw  !

I have tested two things. 

```yaml
additionalConfig:
      plugins.security.audit.type: internal_opensearch
```
Enabling the audit log seems to work.

I am still having problems with PKI and mTLS. The following configuration has no effect:

```yaml
    additionalConfig:
      plugins.security.ssl.http.clientauth_mode: OPTIONAL
```
The entry does not appear in the pod's configuration.

Out of desperation, I tried to give the pod its own configuration with `additionalVolumes`. This of course leads to conflicts. I have no idea what else I could try to enable mTLS.

**Comment by swoehrl-mw** [comment]
Hi @OlafRadicke 

The mechanism used for getting the configuration to opensearch is https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/index/#arguments-at-startup . What I stated in an earlier comment was half-wrong, it does not generate an opensearch.yml with it, the settings are provided directly to the opensearch process.

`plugins.security.audit.type: internal_opensearch` you can see because the operator sets that option itself (https://github.com/opensearch-project/opensearch-k8s-operator/blob/main/opensearch-operator/pkg/reconcilers/configuration.go#L63), so it appears in the config.

`plugins.security.ssl.http.clientauth_mode: OPTIONAL` on the other hand is configured via the mechanism I mentioned. I verified this in a quick test cluster and the cmdline for the running opensearch process includes `-Eplugins.security.ssl.http.clientauth_mode=OPTIONAL`. 

So from the operator side it works as expected. Have you verified if opensearch does what is behind the setting? Even if you do not see it in the pod.

**Comment by OlafRadicke** [comment]
Hi @swoehrl-mw !

I have not found a way to configure the audit log to write to Stdout (debug). I need to be able to dump the audit log so that it can be stored in a tamper-proof manner.

**Comment by OlafRadicke** [comment]
I have now managed it with the audit logs that write to stdout. But I find it confusing when the configuration in the file is used, when the environment variables are used, and when the entrypoint script converts environment variables into program call flags or parameters. When PVC must be deleted and when not. The operator is pure horror.

**Comment by digitalray** [comment]
> I have now managed it with the audit logs that write to stdout. But I find it confusing when the configuration in the file is used, when the environment variables are used, and when the entrypoint script converts environment variables into program call flags or parameters. When PVC must be deleted and when not. The operator is pure horror.

If you were able to somehow add config settings for opensearch, would you mind sharing how?

**Comment by OlafRadicke** [comment]
@digitalray I don't know if I understand the question correctly.
How did I see it or what is my wish, how it should be?
The key-value pairs of bootstrap.additionalConfig are converted by the entrypoint script into process start flags "-E" From

```yaml
[...]
  additionalConfig:
    plugins.security.audit.type: debug
[...]
```
becomes:
```
./openseach -Eplugins.security.audit.type=debug
```
So it should actually be (in my opinion):

```yaml
[...]
  additionalStartArguments:
    plugins.security.audit.type: debug
[...]
````

We hardly use the CRD from https://github.com/opensearch-project/opensearch-k8s-operator/tree/main/opensearch-operator/config/crd/bases. They are poorly documented and we would have to convert a lot of JSON into YAML. Instead, we fill the OpenSearch clusters with Terraform via the REST API. 

The PVCs are a huge problem. Data and configuration are not separated. If you want to reset the configuration, you lose all the indexes. That means downtime. Yes, then I don't need an HA clusters set up either - or?

**Comment by rpasche** [comment]
Can confirm the issue still exists with version `2.8.0`. I was all time wondering, where my *custom* settings are gone, as I did not see them within the config files. Thank you for this *issue*. I would have created one today.

**Comment by pcizmar** [comment]
I have the same issue,

```
# OpenSearchCluster configuration
cluster:
  # OpenSearchCluster general configuration
  general:
    # -- Extra items to add to the opensearch.yml
    additionalConfig:
      logger.level: WARN
      s3.client.default.max_retries: "5" # number of retries if a request fails
      s3.client.default.use_throttle_retries: "true" # whether the client should wait a progressively longer amount of time (exponential backoff) between each successive retry
```

When I specify `s3.client.default.max_retries` and `s3.client.default.use_throttle_retries` under `cluster.general.additionalConfig`, values are added only to `env variables` but not into `opensearch.yml`.

- **env variables:**

```
[opensearch@opensearch-data-9 ~]$ env | grep s3
s3.client.default.max_retries=5
s3.client.default.use_throttle_retries=true
```


- **opensearch.yml:**

```
[opensearch@opensearch-data-9 ~]$ cat config/opensearch.yml 
plugins.security.audit.type: internal_opensearch
plugins.security.authcz.admin_dn: ["CN=xxx,OU=xxx"]
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.nodes_dn: ["CN=xxx,OU=xxx"]
plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.pemcert_filepath: tls-http/tls.crt
plugins.security.ssl.http.pemkey_filepath: tls-http/tls.key
plugins.security.ssl.http.pemtrustedcas_filepath: tls-http/ca.crt
plugins.security.ssl.transport.enforce_hostname_verification: true
plugins.security.ssl.transport.pemcert_filepath: tls-transport/${HOSTNAME}.crt
plugins.security.ssl.transport.pemkey_filepath: tls-transport/${HOSTNAME}.key
plugins.security.ssl.transport.pemtrustedcas_filepath: tls-transport/ca.crt
plugins.security.system_indices.enabled: true
plugins.security.system_indices.indices: [".opendistro-alerting-config",".opendistro-alerting-alert*",".opendistro-anomaly-results*",".opendistro-anomaly-detector*",".opendistro-anomaly-checkpoints",".opendistro-anomaly-detection-state",".opendistro-reports-*",".opendistro-notifications-*",".opendistro-notebooks",".opensearch-observability",".opendistro-asynchronous-search-response*",".replication-metadata-store"]
```

I'm currently using versions:
```
opensearchproject/opensearch:3.2.0
opensearchproject/opensearch-dashboards:3.2.0
busybox:1.37.0
```

Did someone found a workaround how to get those extra items into `opensearch.yml` ?
