### ISSUE TITLE
[BUG] Duplicate image and serviceName variables in opensearch-cluster v3.0.0 helm chart

### ISSUE THREAD

**Issue by rajeshm90** [opensearch-project/opensearch-k8s-operator#939]
### What is the bug?
Getting below error while deploying opensearch-cluster with v3.0.0 helm chart.
```yaml
error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
        line 70: mapping key "image" already defined at line 36
        line 97: mapping key "image" already defined at line 77
        line 98: mapping key "serviceName" already defined at line 92
```

### How can one reproduce the bug?
We can reproduce by running helm template for v3.0.0 too.
* Download the helm chart from v3.0.0
* run `helm template test .` and it returns below
```yaml
  general:
    serviceName: ""
    image: docker.io/opensearchproject/opensearch
    serviceName: test
    image: docker.io/opensearchproject/opensearch:2.3.0

  dashboards:
    image: docker.io/opensearchproject/opensearch-dashboards
    image: docker.io/opensearchproject/opensearch-dashboards:2.3.0
```

### What is the expected behavior?
There shouldn't be any duplicate for the keys under any.

### What is your host/environment?
Kubernetes - `v1.27.11` (same error on latest versions too)
CONTAINER-RUNTIME - `containerd://1.6.23`
OS - `Talos v1.5.3`
Kernel - `6.1.54-talos`
Helm Version - `v3.15.2`

### Do you have any screenshots?
![image](https://github.com/user-attachments/assets/95da7174-1cb8-45eb-a799-28c5e0e8244b)

### Do you have any additional context?
The issue is from the template definition.
* in values.yaml, image and serviceName are defined under `dashboards` and `general` sections. Here both are defined without any versions.
```yaml
cluster:
  general:
    image: docker.io/opensearchproject/opensearch
    serviceName: ""
  dashboards:
    image: docker.io/opensearchproject/opensearch-dashboards
```
* in template `cluster.yaml`, reading all under `dashboards` & `general` section, and additionally image is defined with version.
```yaml
  {{- with .Values.cluster.dashboards }}
  dashboards:
    {{- . | toYaml | nindent 4 }}
    image: {{ .image }}:{{ .version }}
  {{- end }}

  {{- with .Values.cluster.general }}
  general:
    {{- . | toYaml | nindent 4 }}
    image: {{ .image }}:{{ .version }}
    serviceName: {{ .serviceName | default $clusterName }}
  {{- end }}
```
So, `dashboards` and `general` returns two image & serviceName variables!!
