### ISSUE TITLE
[FEATURE] make OpenSearchISMPolicy support email channel notification

### ISSUE THREAD

**Issue by latituder** [opensearch-project/opensearch-k8s-operator#946]
### Is your feature request related to a problem?
_A clear and concise description of what the problem is, e.g. I'm always frustrated when [...]._

I use opensearch Operator deploy my openserach-cluster.
the opensearch Operator also brings a CRD “OpenSearchISMPolicy”, which helps to use a yaml to deinfe ISM.

In the Opensearch UI, if I manually setup an ISM policy, then I can choose a configured notification channel (email), and write an email template.

hoewver, in CR OpenSearchISMPolicy, I see the notifcation doesn’t has email option.
```
$ kc explain OpenSearchISMPolicy.spec.errorNotification.destination
GROUP:      opensearch.opster.io
KIND:       OpenSearchISMPolicy
VERSION:    v1

FIELD: destination <Object>


DESCRIPTION:
    The destination URL.
    
FIELDS:
  amazon        <Object>
    <no description>

  chime <Object>
    <no description>

  customWebhook <Object>
    <no description>

  slack <Object>
    <no description>
```

### What solution would you like?
_A clear and concise description of what you want to happen._
Ideally, I’d like to set the OpenSearchISMPolicy like this:
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchISMPolicy
metadata:
  name: logs-rollover-retention
spec:
  opensearchCluster:
    name: app-logging-opensearch
  description: "set index rollover then wait and retension"
  policyId: logs-rollover-retention
  defaultState: young_indexes
  ismTemplate:
    indexPatterns:
       - logs-*
    priority:  1
  errorNotification:
    channel: my-email-channel # this email channel already configured and tested
    destination: 
        <may I refer an email receiver group name here?>
    messageTemplate:
      source: "APP logging OpenSearch ISM job: The index {{ctx.index}} failed during ISM policy execution"
  states:
    - name: young_indexes
      actions:
.......
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchISMPolicy
metadata:
  name: logs-rollover-retention
spec:
  opensearchCluster:

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by prudhvigodithi** [comment]
[Triage]
Thanks @latituder. `OpenSearchISMPolicy` is for index management, we should have a new CRD for alerting and notifications ?
https://opensearch.org/docs/latest/observing-your-data/notifications/index/
Adding @gaiksaya @swoehrl-mw

**Comment by hjannasch** [comment]
I currently ran into the same issue. The operator does not support a predefined notification channel. The OpenSearch REST API supports an error notification channel-id like this:

```
{
  "error_notification": {
    "channel": {
      "id": "some-channel-config-id"
    },
    "message_template": {
      "source": "The index {{ctx.index}} failed during policy execution"
    }
  }
}
```

My 0perator `OpenSearchISMPolicy` is set like this (but nothing happens, no notification channel is set on ISM policy). Here the `channel` element is a string, not an object with `id` as sub element.
```
errorNotification:
  channel: "some-channel-config-id"
  messageTemplate:
    source: "The index {{ctx.index}} failed during ISM policy execution"
```

@prudhvigodithi Do you think you can support a predefined channel?
