### ISSUE TITLE
[BUG] Special characters aren't well supported in admin password

### ISSUE THREAD

**Issue by DrissiReda** [opensearch-project/opensearch-k8s-operator#955]
You can reproduce it quite simply by creating a cluster with security enabled and using a custom admin password including a character like "*" the cluster won't be able to go up. 

Even tried to query the opensearch cluster via http to debug it and encoded the "*" into "%2A" for my cURL and was denied access.

Simply removing this character and using an alphanumeric password works.

**Comment by andrross** [comment]
[Catch All Triage](https://github.com/opensearch-project/.github/blob/main/TRIAGING.md) - [1](https://github.com/andrross) [2](https://github.com/finnegancarroll) [3](https://github.com/krisfreedain)

**Comment by smithericsmith** [comment]
```
Similar issue.  If your admin password has two $$ chars next to each other, opensearch interprets this as a single $.  e.g. admin password "abcDEF$$12345" interpreted as "abcDEF$12345".  This was using version 2.19.2, deployed in kubernetes via helm chart with:

extraEnvs:
 - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
   value: "abcDEF$$12345"
```
