### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by renaudhager** [opensearch-project/opensearch-k8s-operator#959]
### What is the bug?
The operator allows disabling port 9200 to listen on HTTP only.  However, the readiness probe expects this port to be HTTPS.

### How can one reproduce the bug?
Configure the following in your cluster definition:
```yaml
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-cluster
  namespace: opensearch
spec:
  general:
    additionalConfig:
      plugins.security.ssl.http.enabled: "false"
...
```

### What is the expected behavior?
The readiness probe should handle this case.

### What is your host/environment?
Kubernetes Version: 1.31
OpenSearch Kubernetes Operator Version: 2.7.0
Cloud Provider or Platform: EKS

### Do you have any screenshots?

![Image](https://github.com/user-attachments/assets/4666b237-3150-48b8-8c56-2e485c94ad51)

![Image](https://github.com/user-attachments/assets/309f1e50-a6e8-44d7-956b-2b568914a433)

![Image](https://github.com/user-attachments/assets/d9df792f-97d3-49c3-b221-6a280a1417f0)

### Do you have any additional context?
This would very useful since the current state of the operator prevent it to be use with service mesh and this [PR](https://github.com/opensearch-project/opensearch-k8s-operator/issues/751) is setting idle for almost a year.
