### ISSUE TITLE
[BUG] recovered Opensearch cluster does not start

### ISSUE THREAD

**Issue by L1ghtman2k** [opensearch-project/opensearch-k8s-operator#978]
### What is the bug?
I have started a cluster, then deleted it, while keeping PVC. Recreating the cluster with same credentials and security config causes cluster to not come up.

### How can one reproduce the bug?
1) Provision following resources:
```
apiVersion: v1
data:
  password: ZVpJYUVSamZ5MWFSYU41cm9mMW1CQkhYag==
  username: YWRtaW4=
kind: Secret
type: Opaque
---
apiVersion: v1
data:
  action_groups.yml: X21ldGE6CiAgdHlwZTogImFjdGlvbmdyb3VwcyIKICBjb25maWdfdmVyc2lvbjogMg==
  config.yml: X21ldGE6CiAgdHlwZTogImNvbmZpZyIKICBjb25maWdfdmVyc2lvbjogIjIiCmNvbmZpZzoKICBkeW5hbWljOgogICAgaHR0cDoKICAgICAgYW5vbnltb3VzX2F1dGhfZW5hYmxlZDogZmFsc2UKICAgIGF1dGhjOgogICAgICBiYXNpY19pbnRlcm5hbF9hdXRoX2RvbWFpbjoKICAgICAgICBodHRwX2VuYWJsZWQ6IHRydWUKICAgICAgICB0cmFuc3BvcnRfZW5hYmxlZDogdHJ1ZQogICAgICAgIG9yZGVyOiAiNCIKICAgICAgICBodHRwX2F1dGhlbnRpY2F0b3I6CiAgICAgICAgICB0eXBlOiBiYXNpYwogICAgICAgICAgY2hhbGxlbmdlOiB0cnVlCiAgICAgICAgYXV0aGVudGljYXRpb25fYmFja2VuZDoKICAgICAgICAgIHR5cGU6IGludGVybg==
  internal_users.yml: X21ldGE6CiAgdHlwZTogImludGVybmFsdXNlcnMiCiAgY29uZmlnX3ZlcnNpb246IDIKYWRtaW46CiAgaGFzaDogIiQyYSQxMCQzV3ZneHN0LnNaYThXQ1RWTHJWUHN1V0suTjRkWnVocGcyU1VXVUJYdlF3RURlWGRsdGYveSIKICByZXNlcnZlZDogdHJ1ZQogIGJhY2tlbmRfcm9sZXM6CiAgLSAiYWRtaW4iCiAgZGVzY3JpcHRpb246ICJEZW1vIGFkbWluIHVzZXIi
  nodes_dn.yml: X21ldGE6CiAgdHlwZTogIm5vZGVzZG4iCiAgY29uZmlnX3ZlcnNpb246IDI=
  roles.yml: X21ldGE6CiAgdHlwZTogInJvbGVzIgogIGNvbmZpZ192ZXJzaW9uOiAyCnNlY3VyaXR5X3Jlc3RfYXBpX2FjY2VzczoKICByZXNlcnZlZDogdHJ1ZQojIEFsbG93cyB1c2VycyB0byB2aWV3IG1vbml0b3JzLCBkZXN0aW5hdGlvbnMgYW5kIGFsZXJ0cwphbGVydGluZ19yZWFkX2FjY2VzczoKICByZXNlcnZlZDogdHJ1ZQogIGNsdXN0ZXJfcGVybWlzc2lvbnM6CiAgICAtICdjbHVzdGVyOmFkbWluL29wZW5kaXN0cm8vYWxlcnRpbmcvYWxlcnRzL2dldCcKICAgIC0gJ2NsdXN0ZXI6YWRtaW4vb3BlbmRpc3Ryby9hbGVydGluZy9kZXN0aW5hdGlvbi9nZXQnCiAgICAtICdjbHVzdGVyOmFkbWluL29wZW5kaXN0cm8vYWxlcnRpbmcvbW9uaXRvci9nZXQnCiAgICAtICdjbHVzdGVyOmFkbWluL29wZW5kaXN0cm8vYWxlcnRpbmcvbW9uaXRvci9zZWFyY2gnCiMgQWxsb3dzIHVzZXJzIHRvIHZpZXcgYW5kIGFja25vd2xlZGdlIGFsZXJ0cwphbGVydGluZ19hY2tfYWxlcnRzOgogIHJlc2VydmVkOiB0cnVlCiAgY2x1c3Rlcl9wZXJtaXNzaW9uczoKICAgIC0gJ2NsdXN0ZXI6YWRtaW4vb3BlbmRpc3Ryby9hbGVydGluZy9hbGVydHMvKicKIyBBbGxvd3MgdXNlcnMgdG8gdXNlIGFsbCBhbGVydGluZyBmdW5jdGlvbmFsaXR5CmFsZXJ0aW5nX2Z1bGxfYWNjZXNzOgogIHJlc2VydmVkOiB0cnVlCiAgY2x1c3Rlcl9wZXJtaXNzaW9uczoKICAgIC0gJ2NsdXN0ZXJfbW9uaXRvcicKICAgIC0gJ2NsdXN0ZXI6YWRtaW4vb3BlbmRpc3Ryby9hbGVydGluZy8qJwogIGluZGV4X3Blcm1pc3Npb25zOgogICAgLSBpbmRleF9wYXR0ZXJuczoKICAgICAgICAtICcqJwogICAgICBhbGxvd2VkX2FjdGlvbnM6CiAgICAgICAgLSAnaW5kaWNlc19tb25pdG9yJwogICAgICAgIC0gJ2luZGljZXM6YWRtaW4vYWxpYXNlcy9nZXQnCiAgICAgICAgLSAnaW5kaWNlczphZG1pbi9tYXBwaW5ncy9nZXQnCiMgQWxsb3cgdXNlcnMgdG8gcmVhZCBBbm9tYWx5IERldGVjdGlvbiBkZXRlY3RvcnMgYW5kIHJlc3VsdHMKYW5vbWFseV9yZWFkX2FjY2VzczoKICByZXNlcnZlZDogdHJ1ZQogIGNsdXN0ZXJfcGVybWlzc2lvbnM6CiAgICAtICdjbHVzdGVyOmFkbWluL29wZW5kaXN0cm8vYWQvZGV0ZWN0b3IvaW5mbycKICAgIC0gJ2NsdXN0ZXI6YWRtaW4vb3BlbmRpc3Ryby9hZC9kZXRlY3Rvci9zZWFyY2gnCiAgICAtICdjbHVzdGVyOmFkbWluL29wZW5kaXN0cm8vYWQvZGV0ZWN0b3JzL2dldCcKICAgIC0gJ2NsdXN0ZXI6YWRtaW4vb3BlbmRpc3Ryby9hZC9yZXN1bHQvc2VhcmNoJwogICAgLSAnY2x1c3RlcjphZG1pbi9vcGVuZGlzdHJvL2FkL3Rhc2tzL3NlYXJjaCcKICAgIC0gJ2NsdXN0ZXI6YWRtaW4vb3BlbmRpc3Ryby9hZC9kZXRlY3Rvci92YWxpZGF0ZScKICAgIC0gJ2NsdXN0ZXI6YWRtaW4vb3BlbmRpc3Ryby9hZC9yZXN1bHQvdG9wQW5vbWFsaWVzJwojIEFsbG93cyB1c2VycyB0byB1c2UgYWxsIEFub21hbHkgRGV0ZWN0aW9uIGZ1bmN0aW9uYWxpdHkKYW5vbWFseV9mdWxsX2FjY2VzczoKICByZXNlcnZlZDogdHJ1ZQogIGNsdXN0ZXJfcGVybWlzc2lvbnM6CiAgICAtICdjbHVzdGVyX21vbml0b3InCiAgICAtICdjbHVzdGVyOmFkbWluL29wZW5kaXN0cm8vYWQvKicKICBpbmRleF9wZXJtaXNzaW9uczoKICAgIC0gaW5kZXhfcGF0dGVybnM6CiAgICAgICAgLSAnKicKICAgICAgYWxsb3dlZF9hY3Rpb25zOgogICAgICAgIC0gJ2luZGljZXNfbW9uaXRvcicKICAgICAgICAtICdpbmRpY2VzOmFkbWluL2FsaWFzZXMvZ2V0JwogICAgICAgIC0gJ2luZGljZXM6YWRtaW4vbWFwcGluZ3MvZ2V0JwojIEFsbG93cyB1c2VycyB0byByZWFkIE5vdGVib29rcwpub3RlYm9va3NfcmVhZF9hY2Nlc3M6CiAgcmVzZXJ2ZWQ6IHRydWUKICBjbHVzdGVyX3Blcm1pc3Npb25zOgogICAgLSAnY2x1c3RlcjphZG1pbi9vcGVuZGlzdHJvL25vdGVib29rcy9saXN0JwogICAgLSAnY2x1c3RlcjphZG1pbi9vcGVuZGlzdHJvL25vdGVib29rcy9nZXQnCiMgQWxsb3dzIHVzZXJzIHRvIGFsbCBOb3RlYm9va3MgZnVuY3Rpb25hbGl0eQpub3RlYm9va3NfZnVsbF9hY2Nlc3M6CiAgcmVzZXJ2ZWQ6IHRydWUKICBjbHVzdGVyX3Blcm1pc3Npb25zOgogICAgLSAnY2x1c3RlcjphZG1pbi9vcGVuZGlzdHJvL25vdGVib29rcy9jcmVhdGUnCiAgICAtICdjbHVzdGVyOmFkbWluL29wZW5kaXN0cm8vbm90ZWJvb2tzL3VwZGF0ZScKICAgIC0gJ2NsdXN0ZXI6YWRtaW4vb3BlbmRpc3Ryby9ub3RlYm9va3MvZGVsZXRlJwogICAgLSAnY2x1c3RlcjphZG1pbi9vcGVuZGlzdHJvL25vdGVib29rcy9nZXQnCiAgICAtICdjbHVzdGVyOmFkbWluL29wZW5kaXN0cm8vbm90ZWJvb2tzL2xpc3QnCiMgQWxsb3dzIHVzZXJzIHRvIHJlYWQgb2JzZXJ2YWJpbGl0eSBvYmplY3RzCm9ic2VydmFiaWxpdHlfcmVhZF9hY2Nlc3M6CiAgcmVzZXJ2ZWQ6IHRydWUKICBjbHVzdGVyX3Blcm1pc3Npb25zOgogICAgLSAnY2x1c3RlcjphZG1pbi9vcGVuc2VhcmNoL29ic2VydmFiaWxpdHkvZ2V0JwojIEFsbG93cyB1c2VycyB0byBhbGwgT2JzZXJ2YWJpbGl0eSBmdW5jdGlvbmFsaXR5Cm9ic2VydmFiaWxpdHlfZnVsbF9hY2Nlc3M6CiAgcmVzZXJ2ZWQ6IHRydWUKICBjbHVzdGVyX3Blcm1pc3Npb25zOgogICAgLSAnY2x1c3RlcjphZG1pbi9vcGVuc2VhcmNoL29ic2VydmFiaWxpdHkvY3JlYXRlJwogICAgLSAnY2x1c3RlcjphZG1pbi9vcGVuc2VhcmNoL29ic2VydmFiaWxpdHkvdXBkYXRlJwogICAgLSAnY2x1c3RlcjphZG1pbi9vcGVuc2VhcmNoL29ic2VydmFiaWxpdHkvZGVsZXRlJwogICAgLSAnY2x1c3RlcjphZG1pbi9vcGVuc2VhcmNoL29ic2VydmFiaWxpdHkvZ2V0JwojIEFsbG93cyB1c2VycyB0byByZWFkIGFuZCBkb3dubG9hZCBSZXBvcnRzCnJlcG9ydHNfaW5zdGFuY2VzX3JlYWRfYWNjZXNzOgogIHJlc2VydmVkOiB0cnVlCiAgY2x1c3Rlcl9wZXJtaXNzaW9uczoKICAgIC0gJ2NsdXN0ZXI6YWRtaW4vb3BlbmRpc3Ryby9yZXBvcnRzL2luc3RhbmNlL2xpc3QnCiAgICAtICdjbHVzdGVyOmFkbWluL29wZW5kaXN0cm8vcmVwb3J0cy9pbnN0YW5jZS9nZXQnCiAgICAtICdjbHVzdGVyOmFkbWluL29wZW5kaXN0cm8vcmVwb3J0cy9tZW51L2Rvd25sb2FkJwojIEFsbG93cyB1c2VycyB0byByZWFkIGFuZCBkb3dubG9hZCBSZXBvcnRzIGFuZCBSZXBvcnQtZGVmaW5pdGlvbnMKcmVwb3J0c19yZWFkX2FjY2VzczoKICByZXNlcnZlZDogdHJ1ZQogIGNsdXN0ZXJfcGVybWlzc2lvbnM6CiAgICAtICdjbHVzdGVyOmFkbWluL29wZW5kaXN0cm8vcmVwb3J0cy9kZWZpbml0aW9uL2dldCcKICAgIC0gJ2NsdXN0ZXI6YWRtaW4vb3BlbmRpc3Ryby9yZXBvcnRzL2RlZmluaXRpb24vbGlzdCcKICAgIC0gJ2NsdXN0ZXI6YWRtaW4vb3BlbmRpc3Ryby9yZXBvcnRzL2luc3RhbmNlL2xpc3QnCiAgICAtICdjbHVzdGVyOmFkbWluL29wZW5kaXN0cm8vcmVwb3J0cy9pbnN0YW5jZS9nZXQnCiAgICAtICdjbHVzdGVyOmFkbWluL29wZW5kaXN0cm8vcmVwb3J0cy9tZW51L2Rvd25sb2FkJwojIEFsbG93cyB1c2VycyB0byBhbGwgUmVwb3J0cyBmdW5jdGlvbmFsaXR5CnJlcG9ydHNfZnVsbF9hY2Nlc3M6CiAgcmVzZXJ2ZWQ6IHRydWUKICBjbHVzdGVyX3Blcm1pc3Npb25zOgogICAgLSAnY2x1c3RlcjphZG1pbi9vcGVuZGlzdHJvL3JlcG9ydHMvZGVmaW5pdGlvbi9jcmVhdGUnCiAgICAtICdjbHVzdGVyOmFkbWluL29wZW5kaXN0cm8vcmVwb3J0cy9kZWZpbml0aW9uL3VwZGF0ZScKICAgIC0gJ2NsdXN0ZXI6YWRtaW4vb3BlbmRpc3Ryby9yZXBvcnRzL2RlZmluaXRpb24vb25fZGVtYW5kJwogICAgLSAnY2x1c3RlcjphZG1pbi9vcGVuZGlzdHJvL3JlcG9ydHMvZGVmaW5pdGlvbi9kZWxldGUnCiAgICAtICdjbHVzdGVyOmFkbWluL29wZW5kaXN0cm8vcmVwb3J0cy9kZWZpbml0aW9uL2dldCcKICAgIC0gJ2NsdXN0ZXI6YWRtaW4vb3BlbmRpc3Ryby9yZXBvcnRzL2RlZmluaXRpb24vbGlzdCcKICAgIC0gJ2NsdXN0ZXI6YWRtaW4vb3BlbmRpc3Ryby9yZXBvcnRzL2luc3RhbmNlL2xpc3QnCiAgICAtICdjbHVzdGVyOmFkbWluL29wZW5kaXN0cm8vcmVwb3J0cy9pbnN0YW5jZS9nZXQnCiAgICAtICdjbHVzdGVyOmFkbWluL29wZW5kaXN0cm8vcmVwb3J0cy9tZW51L2Rvd25sb2FkJwojIEFsbG93cyB1c2VycyB0byB1c2UgYWxsIGFzeW5jaHJvbm91cy1zZWFyY2ggZnVuY3Rpb25hbGl0eQphc3luY2hyb25vdXNfc2VhcmNoX2Z1bGxfYWNjZXNzOgogIHJlc2VydmVkOiB0cnVlCiAgY2x1c3Rlcl9wZXJtaXNzaW9uczoKICAgIC0gJ2NsdXN0ZXI6YWRtaW4vb3BlbmRpc3Ryby9hc3luY2hyb25vdXNfc2VhcmNoLyonCiAgaW5kZXhfcGVybWlzc2lvbnM6CiAgICAtIGluZGV4X3BhdHRlcm5zOgogICAgICAgIC0gJyonCiAgICAgIGFsbG93ZWRfYWN0aW9uczoKICAgICAgICAtICdpbmRpY2VzOmRhdGEvcmVhZC9zZWFyY2gqJwojIEFsbG93cyB1c2VycyB0byByZWFkIHN0b3JlZCBhc3luY2hyb25vdXMtc2VhcmNoIHJlc3VsdHMKYXN5bmNocm9ub3VzX3NlYXJjaF9yZWFkX2FjY2VzczoKICByZXNlcnZlZDogdHJ1ZQogIGNsdXN0ZXJfcGVybWlzc2lvbnM6CiAgICAtICdjbHVzdGVyOmFkbWluL29wZW5kaXN0cm8vYXN5bmNocm9ub3VzX3NlYXJjaC9nZXQnCiMgQWxsb3dzIHVzZXIgdG8gdXNlIGFsbCBpbmRleF9tYW5hZ2VtZW50IGFjdGlvbnMgLSBpc20gcG9saWNpZXMsIHJvbGx1cHMsIHRyYW5zZm9ybXMKaW5kZXhfbWFuYWdlbWVudF9mdWxsX2FjY2VzczoKICByZXNlcnZlZDogdHJ1ZQogIGNsdXN0ZXJfcGVybWlzc2lvbnM6CiAgICAtICJjbHVzdGVyOmFkbWluL29wZW5kaXN0cm8vaXNtLyoiCiAgICAtICJjbHVzdGVyOmFkbWluL29wZW5kaXN0cm8vcm9sbHVwLyoiCiAgICAtICJjbHVzdGVyOmFkbWluL29wZW5kaXN0cm8vdHJhbnNmb3JtLyoiCiAgaW5kZXhfcGVybWlzc2lvbnM6CiAgICAtIGluZGV4X3BhdHRlcm5zOgogICAgICAgIC0gJyonCiAgICAgIGFsbG93ZWRfYWN0aW9uczoKICAgICAgICAtICdpbmRpY2VzOmFkbWluL29wZW5zZWFyY2gvaXNtLyonCiMgQWxsb3dzIHVzZXJzIHRvIHVzZSBhbGwgY3Jvc3MgY2x1c3RlciByZXBsaWNhdGlvbiBmdW5jdGlvbmFsaXR5IGF0IGxlYWRlciBjbHVzdGVyCmNyb3NzX2NsdXN0ZXJfcmVwbGljYXRpb25fbGVhZGVyX2Z1bGxfYWNjZXNzOgogIHJlc2VydmVkOiB0cnVlCiAgaW5kZXhfcGVybWlzc2lvbnM6CiAgICAtIGluZGV4X3BhdHRlcm5zOgogICAgICAgIC0gJyonCiAgICAgIGFsbG93ZWRfYWN0aW9uczoKICAgICAgICAtICJpbmRpY2VzOmFkbWluL3BsdWdpbnMvcmVwbGljYXRpb24vaW5kZXgvc2V0dXAvdmFsaWRhdGUiCiAgICAgICAgLSAiaW5kaWNlczpkYXRhL3JlYWQvcGx1Z2lucy9yZXBsaWNhdGlvbi9jaGFuZ2VzIgogICAgICAgIC0gImluZGljZXM6ZGF0YS9yZWFkL3BsdWdpbnMvcmVwbGljYXRpb24vZmlsZV9jaHVuayIKIyBBbGxvd3MgdXNlcnMgdG8gdXNlIGFsbCBjcm9zcyBjbHVzdGVyIHJlcGxpY2F0aW9uIGZ1bmN0aW9uYWxpdHkgYXQgZm9sbG93ZXIgY2x1c3Rlcgpjcm9zc19jbHVzdGVyX3JlcGxpY2F0aW9uX2ZvbGxvd2VyX2Z1bGxfYWNjZXNzOgogIHJlc2VydmVkOiB0cnVlCiAgY2x1c3Rlcl9wZXJtaXNzaW9uczoKICAgIC0gImNsdXN0ZXI6YWRtaW4vcGx1Z2lucy9yZXBsaWNhdGlvbi9hdXRvZm9sbG93L3VwZGF0ZSIKICBpbmRleF9wZXJtaXNzaW9uczoKICAgIC0gaW5kZXhfcGF0dGVybnM6CiAgICAgICAgLSAnKicKICAgICAgYWxsb3dlZF9hY3Rpb25zOgogICAgICAgIC0gImluZGljZXM6YWRtaW4vcGx1Z2lucy9yZXBsaWNhdGlvbi9pbmRleC9zZXR1cC92YWxpZGF0ZSIKICAgICAgICAtICJpbmRpY2VzOmRhdGEvd3JpdGUvcGx1Z2lucy9yZXBsaWNhdGlvbi9jaGFuZ2VzIgogICAgICAgIC0gImluZGljZXM6YWRtaW4vcGx1Z2lucy9yZXBsaWNhdGlvbi9pbmRleC9zdGFydCIKICAgICAgICAtICJpbmRpY2VzOmFkbWluL3BsdWdpbnMvcmVwbGljYXRpb24vaW5kZXgvcGF1c2UiCiAgICAgICAgLSAiaW5kaWNlczphZG1pbi9wbHVnaW5zL3JlcGxpY2F0aW9uL2luZGV4L3Jlc3VtZSIKICAgICAgICAtICJpbmRpY2VzOmFkbWluL3BsdWdpbnMvcmVwbGljYXRpb24vaW5kZXgvc3RvcCIKICAgICAgICAtICJpbmRpY2VzOmFkbWluL3BsdWdpbnMvcmVwbGljYXRpb24vaW5kZXgvdXBkYXRlIgogICAgICAgIC0gImluZGljZXM6YWRtaW4vcGx1Z2lucy9yZXBsaWNhdGlvbi9pbmRleC9zdGF0dXNfY2hlY2si
  roles_mapping.yml: X21ldGE6CiAgdHlwZTogInJvbGVzbWFwcGluZyIKICBjb25maWdfdmVyc2lvbjogMgphbGxfYWNjZXNzOgogIHJlc2VydmVkOiBmYWxzZQogIGJhY2tlbmRfcm9sZXM6CiAgLSAiYWRtaW4iCiAgZGVzY3JpcHRpb246ICJNYXBzIGFkbWluIHRvIGFsbF9hY2Nlc3MiCm93bl9pbmRleDoKICByZXNlcnZlZDogZmFsc2UKICB1c2VyczoKICAtICIqIgogIGRlc2NyaXB0aW9uOiAiQWxsb3cgZnVsbCBhY2Nlc3MgdG8gYW4gaW5kZXggbmFtZWQgbGlrZSB0aGUgdXNlcm5hbWUiCnJlYWRhbGw6CiAgcmVzZXJ2ZWQ6IGZhbHNlCiAgYmFja2VuZF9yb2xlczoKICAtICJyZWFkYWxsIgptYW5hZ2Vfc25hcHNob3RzOgogIHJlc2VydmVkOiBmYWxzZQogIGJhY2tlbmRfcm9sZXM6CiAgLSAic25hcHNob3RyZXN0b3JlIg==
  tenants.yml: X21ldGE6CiAgdHlwZTogInRlbmFudHMiCiAgY29uZmlnX3ZlcnNpb246IDI=
  whitelist.yml: X21ldGE6CiAgdHlwZTogIndoaXRlbGlzdCIKICBjb25maWdfdmVyc2lvbjogMg==
kind: Secret
metadata:
  name: opensearch-cluster-security-config
  namespace: opensearch-ccs
type: Opaque
---
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  annotations:
  finalizers:
  - Opster
  generation: 3
  name: opensearch-cluster
  namespace: opensearch-ccs
spec:
  bootstrap:
    resources: {}
  confMgmt: {}
  dashboards:
    opensearchCredentialsSecret: {}
    replicas: 0
    resources: {}
    service:
      type: ClusterIP
    version: ""
  general:
    additionalConfig:
      compatibility.override_main_response_version: "false"
      path.repo: /usr/share/opensearch/snapshot_repo
    defaultRepo: quay.io/cloudops
    drainDataNodes: false
    httpPort: 9200
    monitoring:
      enable: true
      pluginUrl: file:/usr/share/opensearch/offline-plugins/prometheus-exporter-1.3.9.0.zip
      scrapeInterval: 30s
    pluginsList:
    - file:/usr/share/opensearch/offline-plugins/repository-s3-1.3.9.zip
    serviceName: opensearch-cluster
    setVMMaxMapCount: true
    vendor: opensearch
    version: 1.3.9
  initHelper:
    resources: {}
    version: 1.27.2-buildx
  nodePools:
  - component: masters
    diskSize: 30Gi
    persistence:
      pvc:
        accessModes:
        - ReadWriteOnce
        storageClass: sc-scale
    replicas: 3
    resources:
      limits:
        cpu: "1"
        memory: 4Gi
      requests:
        cpu: "0"
        memory: 0
    roles:
    - master
    - data
  security:
    config:
      adminCredentialsSecret:
        name: opensearch-cluster-admin-password
      adminSecret: {}
      securityConfigSecret:
        name: opensearch-cluster-security-config
    tls:
      http:
        caSecret: {}
        generate: true
        secret: {}
      transport:
        caSecret: {}
        generate: true
        secret: {}
```
2) Remove the cluster while keeping PVCs in tact (delete opensearchcluster)
3) Recreate the cluster(while keeping the admin secret, and securityconfig). In our case, I was testing it by moving these things to a different namespace, and rebinding PVC in that namespace to the Retained PVs

Instead, the cluster never comes up, reporting issues like:
```
join validation on cluster state with a different cluster uuid -_etkE04TQ-zD3zgHShfag than local cluster uuid 1EdPCYhWTlKgLzYhV93xjg, rejecting
```
full log attached

### What is the expected behavior?
The cluster starts up

### What is your host/environment?
ubuntu 20

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
In our case we are trying to move opensearch between k8s clusters
