### ISSUE TITLE
[FEATURE] Allow adding Prometheus relabeling rules through the ServiceMonitor

### ISSUE THREAD

**Issue by mschultz995** [opensearch-project/opensearch-k8s-operator#982]
### Is your feature request related to a problem?
No

### What solution would you like?
Allow configuring relabeling rules through a Cluster Spec "General.Monitoring.Relabeling[]" which is picked up by the Operator when creating the ServiceMonitor.

### What alternatives have you considered?
-

### Do you have any additional context?
-

**Comment by peterzhuamazon** [comment]
Hi @prudhvigodithi could you take a look on this?

Thanks.

**Comment by macrokernel** [comment]
Here is an example of a ServiceMonitor with relabelings for better understanding of the issue, just in case:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: kube-prometheus-stack
  name: opensearch-monitor
  namespace: opensearch
spec:
  endpoints:
  - basicAuth:
      password:
        key: password
        name: monitoring-credentials
      username:
        key: username
        name: monitoring-credentials
    bearerTokenSecret:
      key: ""
      name: ""
    interval: 30s
    path: /_prometheus/metrics
    port: http
    scheme: https
    tlsConfig:
      ca: {}
      cert: {}
      insecureSkipVerify: true
      serverName: opensearch
    relabelings:                        # <--- here
      - action: replace
        sourceLabels:
        - __meta_kubernetes_pod_name
        targetLabel: instance
      - action: replace
        sourceLabels:
        - __meta_kubernetes_namespace
        targetLabel: kubernetes_namespace
  jobLabel: opensearch-monitor
  namespaceSelector:
    matchNames:
    - opensearch
  podTargetLabels:
  - opster.io/opensearch-cluster
  selector:
    matchExpressions:
    - key: opster.io/opensearch-nodepool
      operator: Exists
    matchLabels:
      opster.io/opensearch-cluster: opensearch
  targetLabels:
  - opster.io/opensearch-cluster
```
