### ISSUE TITLE
[BUG] invalid yml file log4j2.properties in securityconfig secret

### ISSUE THREAD

**Issue by lucasfcnunes** [opensearch-project/opensearch-k8s-operator#983]
### What is the bug?
_A clear and concise description of the bug._

```jsonl
{"level":"error","ts":"2025-03-29T23:57:26.898Z","msg":"skipping log4j2.properties","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchCluster":{"name":"opensearch-cluster","namespace":"opensearch"},"namespace":"opensearch","name":"opensearch-cluster","reconcileID":"9d633a89-93f6-4091-b2d5-a6853449e6bb","error":"invalid yml file log4j2.properties in securityconfig secret","stacktrace":"github.com/Opster/opensearch-k8s-operator/opensearch-operator/pkg/reconcilers.BuildCmdArg\n\t/workspace/pkg/reconcilers/securityconfig.go:209\ngithub.com/Opster/opensearch-k8s-operator/opensearch-operator/pkg/reconcilers.(*SecurityconfigReconciler).Reconcile\n\t/workspace/pkg/reconcilers/securityconfig.go:135\ngithub.com/Opster/opensearch-k8s-operator/opensearch-operator/controllers.(*OpenSearchClusterReconciler).reconcilePhaseRunning\n\t/workspace/controllers/opensearchController.go:328\ngithub.com/Opster/opensearch-k8s-operator/opensearch-operator/controllers.(*OpenSearchClusterReconciler).Reconcile\n\t/workspace/controllers/opensearchController.go:143\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226"}
```

### How can one reproduce the bug?
_Steps to reproduce the behavior._

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: securityconfig-secret
stringData:
  # ...
  log4j2.properties: |-
    appender.console.type = Console
    appender.console.name = console
    appender.console.layout.type = OpenSearchJsonLayout
    appender.console.layout.type_name = json_logger
    rootLogger.level = info
    rootLogger.appenderRef.console.ref = console
---
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  annotations:
    meta.helm.sh/release-name: opensearch-cluster
    meta.helm.sh/release-namespace: opensearch
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 2.7.0
    helm.sh/chart: opensearch-cluster-3.0.0
  name: opensearch-cluster
  namespace: opensearch
spec:
  general:
    drainDataNodes: false
    httpPort: 9200
    image: docker.io/opensearchproject/opensearch:2.17.1
    setVMMaxMapCount: true
    vendor: Opensearch
    version: 2.17.1
  initHelper:
    version: "1.36"
  nodePools:
    - component: masters
      diskSize: 10Gi
      env:
        - name: DISABLE_INSTALL_DEMO_CONFIG
          value: "true"
      jvm: -Xmx2880M -Xms2880M
      replicas: 3
      resources:
        limits:
          memory: 3840Mi
        requests:
          cpu: 500m
          memory: 3840Mi
      roles:
        - cluster_manager
        - data
        - data_hot
        - data_cold
        - ingest
  security:
    config:
      # ...
      securityConfigSecret:
        name: securityconfig-secret # <<< !!!
status:
  availableNodes: 3
  componentsStatus:
    - component: Restarter
      status: Finished
  health: green
  initialized: true
  phase: RUNNING
  version: 2.17.1
```

### What is the expected behavior?
_A clear and concise description of what you expected to happen._

No errors log

### What is your host/environment?
_Operating system, version._

- GKE 1.31 COS
- opensearch-cluster/opensearch-cluster 3.0.0
- opensearch-operator/opensearch-operator 2.7.0

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

Using helm charts for cluster and operator
